#!/usr/bin/env python3
"""
Improved script to translate all markdown files in Manual_en from Chinese to English
"""

import os
import re
import glob
from pathlib import Path

# Common Chinese phrases and their English translations
COMMON_PHRASES = {
    "用户可通过": "Users can",
    "支持": "Supports",
    "提供": "Provides",
    "创建": "Create",
    "管理": "Manage",
    "配置": "Configure", 
    "用于": "Used for",
    "可以": "can",
    "能够": "able to",
    "进行": "perform",
    "包括": "including",
    "以及": "and",
    "或": "or",
    "等": "etc.",
    "的": "",
    "是": "is",
    "为": "for",
    "在": "in",
    "中": "",
    "从": "from",
    "到": "to",
    "与": "and",
    "和": "and",
    "或": "or",
    "但": "but",
    "如果": "If",
    "当": "When",
    "通过": "through",
    "使用": "use",
    "点击": "Click",
    "输入": "Enter",
    "选择": "Select",
    "设置": "Set",
    "修改": "Modify",
    "更新": "Update",
    "删除": "Delete",
    "添加": "Add",
    "查看": "View",
    "显示": "Display",
    "生成": "Generate",
    "获取": "Obtain",
    "处理": "Process",
    "执行": "Execute",
    "运行": "Run",
    "启动": "Start",
    "停止": "Stop",
    "暂停": "Pause",
    "继续": "Continue",
    "完成": "Complete",
    "开始": "Begin",
    "结束": "End",
    "第一": "First",
    "第二": "Second", 
    "第三": "Third",
    "第四": "Fourth",
    "第五": "Fifth",
    "步骤": "Step",
    "阶段": "Phase",
    "流程": "Process",
    "方法": "Method",
    "方式": "Way",
    "途径": "Approach",
    "技术": "Technology",
    "工具": "Tool",
    "功能": "Function",
    "特性": "Feature",
    "模块": "Module",
    "组件": "Component",
    "系统": "System",
    "平台": "Platform",
    "服务": "Service",
    "接口": "Interface",
    "协议": "Protocol",
    "格式": "Format",
    "类型": "Type",
    "模式": "Mode",
    "状态": "Status",
    "结果": "Result",
    "输出": "Output",
    "输入": "Input",
    "参数": "Parameter",
    "选项": "Option",
    "设置": "Setting",
    "配置": "Configuration",
    "数据": "Data",
    "信息": "Information",
    "内容": "Content",
    "文档": "Document",
    "文件": "File",
    "记录": "Record",
    "日志": "Log",
    "报告": "Report",
    "列表": "List",
    "表格": "Table",
    "图表": "Chart",
    "图像": "Image",
    "文本": "Text",
    "数字": "Number",
    "值": "Value",
    "键": "Key",
    "ID": "ID",
    "名称": "Name",
    "标题": "Title",
    "描述": "Description",
    "说明": "Description",
    "注释": "Comment",
    "备注": "Note",
    "示例": "Example",
    "案例": "Case",
    "场景": "Scenario",
    "情况": "Situation",
    "问题": "Problem",
    "解决方案": "Solution",
    "要求": "Requirement",
    "需求": "Demand",
    "条件": "Condition",
    "限制": "Limitation",
    "约束": "Constraint",
    "规则": "Rule",
    "标准": "Standard",
    "规范": "Specification",
    "指南": "Guide",
    "手册": "Manual",
    "教程": "Tutorial",
    "文档": "Documentation",
    "参考": "Reference",
    "链接": "Link",
    "地址": "Address",
    "路径": "Path",
    "URL": "URL",
    "连接": "Connection",
    "会话": "Session",
    "请求": "Request",
    "响应": "Response",
    "错误": "Error",
    "异常": "Exception",
    "警告": "Warning",
    "提示": "Tip",
    "消息": "Message",
    "通知": "Notification",
    "事件": "Event",
    "操作": "Operation",
    "动作": "Action",
    "行为": "Behavior",
    "权限": "Permission",
    "认证": "Authentication",
    "授权": "Authorization",
    "安全": "Security",
    "隐私": "Privacy",
    "保护": "Protection",
    "检查": "Check",
    "验证": "Validate",
    "测试": "Test",
    "调试": "Debug",
    "优化": "Optimize",
    "改进": "Improve",
    "增强": "Enhance",
    "扩展": "Extend",
    "集成": "Integrate",
    "部署": "Deploy",
    "安装": "Install",
    "配置": "Configure",
    "管理": "Manage",
    "维护": "Maintain",
    "支持": "Support",
    "帮助": "Help",
    "支持": "Support",
    "文档": "Documentation",
    "指南": "Guide",
    "教程": "Tutorial",
    "示例": "Example",
    "参考": "Reference",
    "手册": "Manual",
    "文档": "Documentation",
    "说明": "Instructions",
    "介绍": "Introduction",
    "概述": "Overview",
    "摘要": "Summary",
    "总结": "Conclusion",
    "结论": "Conclusion",
    "建议": "Recommendation",
    "意见": "Opinion",
    "观点": "View",
    "立场": "Position",
    "态度": "Attitude",
    "公司": "Company",
    "企业": "Enterprise",
    "组织": "Organization",
    "团队": "Team",
    "部门": "Department",
    "员工": "Employee",
    "管理员": "Administrator",
    "用户": "User",
    "客户": "Customer",
    "访客": "Visitor",
    "成员": "Member",
    "角色": "Role",
    "职责": "Responsibility",
    "任务": "Task",
    "工作": "Work",
    "项目": "Project",
    "计划": "Plan",
    "目标": "Goal",
    "目的": "Purpose",
    "愿景": "Vision",
    "使命": "Mission",
    "战略": "Strategy",
    "方案": "Plan",
    "措施": "Measure",
    "方法": "Method",
    "技术": "Technology",
    "工具": "Tool",
    "设备": "Equipment",
    "硬件": "Hardware",
    "软件": "Software",
    "系统": "System",
    "平台": "Platform",
    "应用": "Application",
    "程序": "Program",
    "代码": "Code",
    "脚本": "Script",
    "算法": "Algorithm",
    "模型": "Model",
    "数据": "Data",
    "数据库": "Database",
    "存储": "Storage",
    "内存": "Memory",
    "网络": "Network",
    "连接": "Connection",
    "接口": "Interface",
    "端口": "Port",
    "协议": "Protocol",
    "标准": "Standard",
    "格式": "Format",
    "编码": "Encoding",
    "解码": "Decoding",
    "加密": "Encryption",
    "解密": "Decryption",
    "压缩": "Compression",
    "解压": "Decompression",
    "转换": "Convert",
    "解析": "Parse",
    "格式化": "Format",
    "验证": "Validate",
    "检查": "Check",
    "测试": "Test",
    "监控": "Monitor",
    "分析": "Analysis",
    "报告": "Report",
    "统计": "Statistics",
    "计算": "Calculate",
    "处理": "Process",
    "操作": "Operate",
    "控制": "Control",
    "管理": "Manage",
    "配置": "Configure",
    "设置": "Setup",
    "安装": "Install",
    "部署": "Deploy",
    "运行": "Run",
    "启动": "Start",
    "停止": "Stop",
    "重启": "Restart",
    "暂停": "Pause",
    "继续": "Continue",
    "完成": "Complete",
    "结束": "End",
    "退出": "Exit",
    "返回": "Return",
    "前进": "Forward",
    "后退": "Back",
    "刷新": "Refresh",
    "重新加载": "Reload",
    "下载": "Download",
    "上传": "Upload",
    "导入": "Import",
    "导出": "Export",
    "复制": "Copy",
    "粘贴": "Paste",
    "剪切": "Cut",
    "删除": "Delete",
    "移动": "Move",
    "重命名": "Rename",
    "编辑": "Edit",
    "修改": "Modify",
    "更新": "Update",
    "创建": "Create",
    "新建": "New",
    "打开": "Open",
    "关闭": "Close",
    "保存": "Save",
    "另存为": "Save As",
    "打印": "Print",
    "预览": "Preview",
    "搜索": "Search",
    "查找": "Find",
    "替换": "Replace",
    "过滤": "Filter",
    "排序": "Sort",
    "分组": "Group",
    "选择": "Select",
    "取消选择": "Deselect",
    "全选": "Select All",
    "清空": "Clear",
    "重置": "Reset",
    "还原": "Restore",
    "撤销": "Undo",
    "重做": "Redo",
    "确认": "Confirm",
    "取消": "Cancel",
    "确定": "OK",
    "应用": "Apply",
    "提交": "Submit",
    "发送": "Send",
    "接收": "Receive",
    "获取": "Get",
    "设置": "Set",
    "修改": "Change",
    "删除": "Remove",
    "添加": "Add",
    "插入": "Insert",
    "编辑": "Edit",
    "更新": "Update",
    "保存": "Save",
    "加载": "Load",
    "初始化": "Initialize",
    "配置": "Configure",
    "启用": "Enable",
    "禁用": "Disable",
    "激活": "Activate",
    "停用": "Deactivate",
    "注册": "Register",
    "登录": "Login",
    "登出": "Logout",
    "认证": "Authenticate",
    "授权": "Authorize",
    "验证": "Verify",
    "刷新": "Refresh",
    "同步": "Synchronize",
    "备份": "Backup",
    "恢复": "Recover",
    "还原": "Restore",
    "重置": "Reset",
    "清理": "Clean",
    "优化": "Optimize",
    "修复": "Fix",
    "解决": "Solve",
    "处理": "Handle",
    "管理": "Manage",
    "维护": "Maintain",
    "监控": "Monitor",
    "记录": "Record",
    "日志": "Log",
    "审计": "Audit",
    "跟踪": "Track",
    "分析": "Analyze",
    "报告": "Report",
    "统计": "Statistics",
    "计算": "Calculate",
    "处理": "Process",
    "执行": "Execute",
    "运行": "Run",
    "操作": "Operate",
    "控制": "Control",
    "命令": "Command",
    "指令": "Instruction",
    "请求": "Request",
    "响应": "Response",
    "消息": "Message",
    "事件": "Event",
    "通知": "Notification",
    "警告": "Warning",
    "错误": "Error",
    "异常": "Exception",
    "故障": "Failure",
    "问题": "Issue",
    "缺陷": "Bug",
    "漏洞": "Vulnerability",
    "风险": "Risk",
    "威胁": "Threat",
    "攻击": "Attack",
    "防护": "Protection",
    "安全": "Security",
    "隐私": "Privacy",
    "保护": "Protection",
    "加密": "Encryption",
    "解密": "Decryption",
    "签名": "Signature",
    "验证": "Verification",
    "认证": "Authentication",
    "授权": "Authorization",
    "权限": "Permission",
    "访问": "Access",
    "控制": "Control",
    "管理": "Management",
    "策略": "Policy",
    "规则": "Rule",
    "配置": "Configuration",
    "设置": "Setting",
    "选项": "Option",
    "参数": "Parameter",
    "变量": "Variable",
    "常量": "Constant",
    "属性": "Property",
    "字段": "Field",
    "记录": "Record",
    "条目": "Entry",
    "项目": "Item",
    "元素": "Element",
    "节点": "Node",
    "分支": "Branch",
    "树": "Tree",
    "列表": "List",
    "数组": "Array",
    "集合": "Collection",
    "映射": "Map",
    "字典": "Dictionary",
    "对象": "Object",
    "实例": "Instance",
    "类": "Class",
    "接口": "Interface",
    "方法": "Method",
    "函数": "Function",
    "过程": "Procedure",
    "操作": "Operation",
    "动作": "Action",
    "行为": "Behavior",
    "事件": "Event",
    "状态": "State",
    "条件": "Condition",
    "循环": "Loop",
    "分支": "Branch",
    "判断": "Decision",
    "选择": "Selection",
    "排序": "Sort",
    "搜索": "Search",
    "查找": "Find",
    "过滤": "Filter",
    "映射": "Mapping",
    "转换": "Transform",
    "处理": "Process",
    "计算": "Compute",
    "分析": "Analyze",
    "评估": "Evaluate",
    "比较": "Compare",
    "匹配": "Match",
    "关联": "Associate",
    "连接": "Connect",
    "绑定": "Bind",
    "链接": "Link",
    "引用": "Reference",
    "指针": "Pointer",
    "索引": "Index",
    "键": "Key",
    "值": "Value",
    "数据": "Data",
    "信息": "Information",
    "内容": "Content",
    "文本": "Text",
    "字符": "Character",
    "字符串": "String",
    "数字": "Number",
    "整数": "Integer",
    "浮点数": "Float",
    "布尔值": "Boolean",
    "日期": "Date",
    "时间": "Time",
    "时间戳": "Timestamp",
    "格式": "Format",
    "编码": "Encoding",
    "解码": "Decoding",
    "序列化": "Serialization",
    "反序列化": "Deserialization",
    "压缩": "Compression",
    "解压": "Decompression",
    "打包": "Package",
    "解包": "Unpack",
    "传输": "Transmission",
    "接收": "Reception",
    "发送": "Sending",
    "同步": "Synchronization",
    "异步": "Asynchronous",
    "并发": "Concurrency",
    "并行": "Parallel",
    "串行": "Serial",
    "队列": "Queue",
    "栈": "Stack",
    "缓冲区": "Buffer",
    "缓存": "Cache",
    "内存": "Memory",
    "磁盘": "Disk",
    "文件": "File",
    "目录": "Directory",
    "路径": "Path",
    "名称": "Name",
    "扩展名": "Extension",
    "大小": "Size",
    "长度": "Length",
    "宽度": "Width",
    "高度": "Height",
    "位置": "Position",
    "坐标": "Coordinates",
    "区域": "Area",
    "范围": "Range",
    "边界": "Boundary",
    "限制": "Limit",
    "约束": "Constraint",
    "规则": "Rule",
    "条件": "Condition",
    "要求": "Requirement",
    "规范": "Specification",
    "标准": "Standard",
    "协议": "Protocol",
    "接口": "Interface",
    "格式": "Format",
    "模板": "Template",
    "样式": "Style",
    "主题": "Theme",
    "布局": "Layout",
    "设计": "Design",
    "架构": "Architecture",
    "结构": "Structure",
    "组织": "Organization",
    "层次": "Hierarchy",
    "级别": "Level",
    "层级": "Layer",
    "模块": "Module",
    "组件": "Component",
    "部件": "Part",
    "元素": "Element",
    "单元": "Unit",
    "实例": "Instance",
    "对象": "Object",
    "实体": "Entity",
    "记录": "Record",
    "行": "Row",
    "列": "Column",
    "单元格": "Cell",
    "表": "Table",
    "视图": "View",
    "页面": "Page",
    "窗口": "Window",
    "对话框": "Dialog",
    "菜单": "Menu",
    "工具栏": "Toolbar",
    "状态栏": "Status Bar",
    "滚动条": "Scrollbar",
    "按钮": "Button",
    "链接": "Link",
    "标签": "Label",
    "文本框": "Text Box",
    "复选框": "Checkbox",
    "单选按钮": "Radio Button",
    "下拉列表": "Dropdown List",
    "列表框": "List Box",
    "图像": "Image",
    "图标": "Icon",
    "图形": "Graphic",
    "图表": "Chart",
    "动画": "Animation",
    "视频": "Video",
    "音频": "Audio",
    "媒体": "Media",
    "播放": "Play",
    "暂停": "Pause",
    "停止": "Stop",
    "录制": "Record",
    "编辑": "Edit",
    "剪切": "Cut",
    "复制": "Copy",
    "粘贴": "Paste",
    "删除": "Delete",
    "插入": "Insert",
    "修改": "Modify",
    "更新": "Update",
    "保存": "Save",
    "加载": "Load",
    "导入": "Import",
    "导出": "Export",
    "打印": "Print",
    "预览": "Preview",
    "缩放": "Zoom",
    "旋转": "Rotate",
    "移动": "Move",
    "调整大小": "Resize",
    "对齐": "Align",
    "分布": "Distribute",
    "组合": "Group",
    "取消组合": "Ungroup",
    "锁定": "Lock",
    "解锁": "Unlock",
    "隐藏": "Hide",
    "显示": "Show",
    "折叠": "Collapse",
    "展开": "Expand",
    "最小化": "Minimize",
    "最大化": "Maximize",
    "还原": "Restore",
    "关闭": "Close",
    "打开": "Open",
    "新建": "New",
    "创建": "Create",
    "删除": "Delete",
    "重命名": "Rename",
    "复制": "Copy",
    "移动": "Move",
    "浏览": "Browse",
    "搜索": "Search",
    "查找": "Find",
    "替换": "Replace",
    "过滤": "Filter",
    "排序": "Sort",
    "分组": "Group",
    "选择": "Select",
    "清空": "Clear",
    "重置": "Reset",
    "刷新": "Refresh",
    "同步": "Synchronize",
    "备份": "Backup",
    "恢复": "Restore",
    "还原": "Revert",
    "撤销": "Undo",
    "重做": "Redo",
    "重复": "Repeat",
    "应用": "Apply",
    "确定": "OK",
    "取消": "Cancel",
    "确认": "Confirm",
    "提交": "Submit",
    "发送": "Send",
    "接收": "Receive",
    "下载": "Download",
    "上传": "Upload",
    "安装": "Install",
    "卸载": "Uninstall",
    "配置": "Configure",
    "设置": "Setup",
    "管理": "Manage",
    "维护": "Maintain",
    "监控": "Monitor",
    "分析": "Analyze",
    "报告": "Report",
    "日志": "Log",
    "记录": "Record",
    "历史": "History",
    "统计": "Statistics",
    "信息": "Information",
    "详情": "Details",
    "属性": "Properties",
    "设置": "Settings",
    "选项": "Options",
    "参数": "Parameters",
    "配置": "Configuration",
    "状态": "Status",
    "进度": "Progress",
    "结果": "Results",
    "输出": "Output",
    "输入": "Input",
    "数据": "Data",
    "文件": "File",
    "目录": "Directory",
    "路径": "Path",
    "名称": "Name",
    "类型": "Type",
    "大小": "Size",
    "日期": "Date",
    "时间": "Time",
    "创建者": "Creator",
    "修改者": "Modifier",
    "所有者": "Owner",
    "权限": "Permissions",
    "访问控制": "Access Control",
    "安全": "Security",
    "加密": "Encryption",
    "解密": "Decryption",
    "签名": "Signature",
    "验证": "Verification",
    "认证": "Authentication",
    "授权": "Authorization",
    "令牌": "Token",
    "密钥": "Key",
    "密码": "Password",
    "账户": "Account",
    "用户名": "Username",
    "邮箱": "Email",
    "电话": "Phone",
    "地址": "Address",
    "联系": "Contact",
    "公司": "Company",
    "组织": "Organization",
    "部门": "Department",
    "职位": "Position",
    "角色": "Role",
    "团队": "Team",
    "项目": "Project",
    "任务": "Task",
    "活动": "Activity",
    "事件": "Event",
    "会议": "Meeting",
    "讨论": "Discussion",
    "评论": "Comment",
    "反馈": "Feedback",
    "建议": "Suggestion",
    "意见": "Opinion",
    "评级": "Rating",
    "评分": "Score",
    "投票": "Vote",
    "调查": "Survey",
    "问卷": "Questionnaire",
    "表单": "Form",
    "申请": "Application",
    "请求": "Request",
    "订单": "Order",
    "交易": "Transaction",
    "支付": "Payment",
    "发票": "Invoice",
    "收据": "Receipt",
    "货币": "Currency",
    "价格": "Price",
    "成本": "Cost",
    "预算": "Budget",
    "费用": "Fee",
    "收入": "Income",
    "支出": "Expense",
    "利润": "Profit",
    "亏损": "Loss",
    "资产": "Asset",
    "负债": "Liability",
    "资本": "Capital",
    "投资": "Investment",
    "回报": "Return",
    "利息": "Interest",
    "汇率": "Exchange Rate",
    "税率": "Tax Rate",
    "折扣": "Discount",
    "优惠": "Promotion",
    "促销": "Sale",
    "广告": "Advertisement",
    "营销": "Marketing",
    "销售": "Sales",
    "客户": "Customer",
    "消费者": "Consumer",
    "市场": "Market",
    "竞争": "Competition",
    "分析": "Analysis",
    "研究": "Research",
    "开发": "Development",
    "设计": "Design",
    "测试": "Test",
    "部署": "Deployment",
    "发布": "Release",
    "版本": "Version",
    "更新": "Update",
    "升级": "Upgrade",
    "补丁": "Patch",
    "修复": "Fix",
    "错误": "Error",
    "缺陷": "Bug",
    "问题": "Issue",
    "故障": "Failure",
    "异常": "Exception",
    "警告": "Warning",
    "提示": "Hint",
    "帮助": "Help",
    "文档": "Documentation",
    "手册": "Manual",
    "指南": "Guide",
    "教程": "Tutorial",
    "示例": "Example",
    "演示": "Demo",
    "模板": "Template",
    "样例": "Sample",
    "参考": "Reference",
    "规范": "Specification",
    "标准": "Standard",
    "协议": "Protocol",
    "接口": "Interface",
    "API": "API",
    "SDK": "SDK",
    "框架": "Framework",
    "库": "Library",
    "插件": "Plugin",
    "扩展": "Extension",
    "模块": "Module",
    "组件": "Component",
    "服务": "Service",
    "微服务": "Microservice",
    "容器": "Container",
    "镜像": "Image",
    "编排": "Orchestration",
    "集群": "Cluster",
    "节点": "Node",
    "实例": "Instance",
    "虚拟化": "Virtualization",
    "云": "Cloud",
    "本地": "Local",
    "远程": "Remote",
    "分布式": "Distributed",
    "集中式": "Centralized",
    "架构": "Architecture",
    "设计": "Design",
    "模式": "Pattern",
    "最佳实践": "Best Practice",
    "经验": "Experience",
    "知识": "Knowledge",
    "技能": "Skill",
    "能力": "Capability",
    "素养": "Literacy",
    "学习": "Learning",
    "培训": "Training",
    "教育": "Education",
    "课程": "Course",
    "认证": "Certification",
    "资格": "Qualification",
    "证书": "Certificate",
    "授权": "License",
    "许可": "Permission",
    "合规": "Compliance",
    "法律": "Law",
    "法规": "Regulation",
    "政策": "Policy",
    "条款": "Terms",
    "条件": "Conditions",
    "协议": "Agreement",
    "合同": "Contract",
    "责任": "Responsibility",
    "义务": "Duty",
    "权利": "Right",
    "利益": "Interest",
    "风险": "Risk",
    "评估": "Assessment",
    "管理": "Management",
    "治理": "Governance",
    "监督": "Supervision",
    "审计": "Audit",
    "检查": "Inspection",
    "审核": "Review",
    "批准": "Approval",
    "拒绝": "Rejection",
    "接受": "Acceptance",
    "完成": "Completion",
    "成功": "Success",
    "失败": "Failure",
    "结果": "Result",
    "成果": "Outcome",
    "效果": "Effect",
    "影响": "Impact",
    "作用": "Function",
    "目的": "Purpose",
    "目标": "Goal",
    "宗旨": "Mission",
    "愿景": "Vision",
    "价值观": "Values",
    "原则": "Principles",
    "理念": "Philosophy",
    "文化": "Culture",
    "环境": "Environment",
    "条件": "Conditions",
    "因素": "Factors",
    "要素": "Elements",
    "方面": "Aspects",
    "领域": "Field",
    "范围": "Scope",
    "区域": "Region",
    "地方": "Place",
    "位置": "Location",
    "地点": "Spot",
    "场所": "Venue",
    "设施": "Facility",
    "设备": "Equipment",
    "工具": "Tools",
    "资源": "Resources",
    "材料": "Materials",
    "供应": "Supply",
    "需求": "Demand",
    "库存": "Inventory",
    "存储": "Storage",
    "仓库": "Warehouse",
    "物流": "Logistics",
    "运输": "Transportation",
    "配送": "Delivery",
    "网络": "Network",
    "连接": "Connection",
    "通信": "Communication",
    "传输": "Transmission",
    "带宽": "Bandwidth",
    "速度": "Speed",
    "延迟": "Latency",
    "吞吐量": "Throughput",
    "性能": "Performance",
    "效率": "Efficiency",
    "效果": "Effectiveness",
    "质量": "Quality",
    "可靠性": "Reliability",
    "可用性": "Availability",
    "可扩展性": "Scalability",
    "灵活性": "Flexibility",
    "适应性": "Adaptability",
    "稳定性": "Stability",
    "一致性": "Consistency",
    "准确性": "Accuracy",
    "精确性": "Precision",
    "及时性": "Timeliness",
    "完整性": "Integrity",
    "安全性": "Security",
    "保密性": "Confidentiality",
    "私密性": "Privacy",
    "透明度": "Transparency",
    "可视化": "Visualization",
    "交互": "Interaction",
    "体验": "Experience",
    "界面": "Interface",
    "用户界面": "User Interface",
    "用户体验": "User Experience",
    "可用性": "Usability",
    "无障碍": "Accessibility",
    "国际化": "Internationalization",
    "本地化": "Localization",
    "多语言": "Multilingual",
    "多地区": "Multi-region",
    "全球化": "Globalization",
    "标准化": "Standardization",
    "规范化": "Normalization",
    "自动化": "Automation",
    "智能化": "Intelligent",
    "数字化": "Digitalization",
    "信息化": "Informatization",
    "网络化": "Networked",
    "平台化": "Platformization",
    "服务化": "Servitization",
    "产品化": "Productization",
    "商业化": "Commercialization",
    "产业化": "Industrialization",
    "规模化": "Scaling",
    "优化": "Optimization",
    "改进": "Improvement",
    "创新": "Innovation",
    "变革": "Transformation",
    "改革": "Reform",
    "升级": "Upgrade",
    "演进": "Evolution",
    "发展": "Development",
    "增长": "Growth",
    "扩展": "Expansion",
    "延伸": "Extension",
    "深化": "Deepening",
    "细化": "Refinement",
    "简化": "Simplification",
    "集成": "Integration",
    "整合": "Consolidation",
    "合并": "Merger",
    "分离": "Separation",
    "拆分": "Split",
    "重组": "Reorganization",
    "调整": "Adjustment",
    "修改": "Modification",
    "变更": "Change",
    "更新": "Update",
    "维护": "Maintenance",
    "支持": "Support",
    "保障": "Ensurance",
    "促进": "Promotion",
    "推动": "Driving",
    "引导": "Guidance",
    "协调": "Coordination",
    "合作": "Cooperation",
    "协作": "Collaboration",
    "共享": "Sharing",
    "交流": "Exchange",
    "沟通": "Communication",
    "联系": "Contact",
    "互动": "Interaction",
    "参与": "Participation",
    "贡献": "Contribution",
    "投入": "Investment",
    "资源": "Resource",
    "资本": "Capital",
    "资产": "Asset",
    "财产": "Property",
    "权益": "Equity",
    "所有权": "Ownership",
    "控制权": "Control",
    "管理权": "Management",
    "使用权": "Usage Rights",
    "访问权": "Access Rights",
    "知识产权": "Intellectual Property",
    "专利": "Patent",
    "商标": "Trademark",
    "版权": "Copyright",
    "许可": "License",
    "授权": "Authorization",
    "转让": "Transfer",
    "许可协议": "License Agreement",
    "服务条款": "Terms of Service",
    "使用条款": "Terms of Use",
    "隐私政策": "Privacy Policy",
    "Cookie政策": "Cookie Policy",
    "数据保护": "Data Protection",
    "个人信息": "Personal Information",
    "敏感信息": "Sensitive Information",
    "机密信息": "Confidential Information",
    "公开信息": "Public Information",
    "内部信息": "Internal Information",
    "外部信息": "External Information",
}

def translate_text_improved(text):
    """
    Improved translation function using context-aware translation
    """
    # Split text into lines first
    lines = text.split('\n')
    translated_lines = []
    
    for line in lines:
        # Skip lines without Chinese or already English
        if not re.search(r'[\u4e00-\u9fff]', line):
            translated_lines.append(line)
            continue
            
        original_line = line.strip()
        translated_line = original_line
        
        # Handle common sentence patterns
        patterns = [
            (r'可通过(.+?)，(.+)', r'\1 can \2'),
            (r'通过(.+?)可以(.+)', r'Through \1, you can \2'),
            (r'支持(.+?)，(.+)', r'Supports \1, \2'),
            (r'提供(.+?)，(.+)', r'Provides \1, \2'),
            (r'用于(.+?)，(.+)', r'Used for \1, \2'),
            (r'点击(.+?)，(.+)', r'Click \1 to \2'),
            (r'在(.+?)中(.+)', r'In \1, \2'),
            (r'(.+?)的(.+?)', r'\1 \2'),
            (r'是(.+?)的(.+)', r'\1 is a \2'),
            (r'为(.+?)提供(.+)', r'Provide \2 for \1'),
            (r'可以(.+)', r'Can \1'),
            (r'能够(.+)', r'Able to \1'),
            (r'进行(.+)', r'Perform \1'),
            (r'使用(.+)', r'Use \1'),
            (r'包括(.+)', r'Including \1'),
            (r'以及(.+)', r'and \1'),
            (r'或者(.+)', r'or \1'),
            (r'以及(.+)', r'and \1'),
            (r'等(.+)', r'etc.'),
        ]
        
        for pattern, replacement in patterns:
            translated_line = re.sub(pattern, replacement, translated_line)
        
        # Replace common terms
        for chinese, english in COMMON_PHRASES.items():
            translated_line = translated_line.replace(chinese, english)
        
        # Handle punctuation
        translated_line = re.sub(r'[，。！？；：""''（）【】《》]', lambda m: {
            '，': ', ',
            '。': '. ',
            '！': '! ',
            '？': '? ',
            '；': '; ',
            '：': ': ',
            '"': '"',
            '"': '"',
            ''': "'",
            ''': "'",
            '（': '(',
            '）': ')',
            '【': '[',
            '】': ']',
            '《': '"',
            '》': '"'
        }.get(m.group(0), m.group(0)), translated_line)
        
        # Clean up spaces
        translated_line = re.sub(r'\s*([,.!?;:])\s*', r'\1 ', translated_line)
        translated_line = re.sub(r'\s+', ' ', translated_line)
        
        if translated_line.strip():  # Only add non-empty lines
            translated_lines.append(translated_line.strip())
    
    # Rejoin lines and fix formatting
    result = '\n'.join(translated_lines)
    
    # Fix markdown headers
    result = re.sub(r'^(#+)\s*(.+)$', lambda m: m.group(1) + ' ' + m.group(2).strip(), result, flags=re.MULTILINE)
    
    # Fix numbered lists  
    result = re.sub(r'^(\d+)\)[\s.]+(.*)$', r'\1. \2', result, flags=re.MULTILINE)
    
    # Fix bullet points
    result = re.sub(r'^[-*+]\s*(.*)$', r'- \1', result, flags=re.MULTILINE)
    
    # Add proper spacing around headers
    result = re.sub(r'\n(#+\s+[^\n]+)\n', r'\n\1\n\n', result)
    
    return result.strip()

def translate_markdown_file_improved(file_path):
    """
    Improved translation function
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Only translate if content contains Chinese characters
        if re.search(r'[\u4e00-\u9fff]', content):
            translated_content = translate_text_improved(content)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(translated_content)
            
            print(f"Translated improved: {file_path}")
            return True
        else:
            print(f"No Chinese content found in: {file_path}")
            return False
            
    except Exception as e:
        print(f"Error translating {file_path}: {e}")
        return False

def main():
    """
    Main function to translate all markdown files
    """
    manual_en_dir = "/Users/mohankumarv/Desktop/SAFVR/wanwu/configs/microservice/bff-service/static/Manual_en"
    
    # Find all markdown files recursively
    md_files = glob.glob(f"{manual_en_dir}/**/*.md", recursive=True)
    
    print(f"Found {len(md_files)} markdown files to translate with improved method")
    
    translated_count = 0
    for md_file in md_files:
        # Skip files we already manually translated
        if os.path.basename(md_file) in ["0.Platform Introduction.md", "2.Knowledge Base/Hit Testing/Create Hit Test.md", "5.Text QA.md"]:
            continue
            
        if translate_markdown_file_improved(md_file):
            translated_count += 1
    
    print(f"Improved translation complete! Translated {translated_count} additional files.")

if __name__ == "__main__":
    main()
