#!/usr/bin/env python3
"""
Script to translate all markdown files in Manual_en from Chinese to English
"""

import os
import re
import glob
from pathlib import Path

# Dictionary for common Chinese terms and their English translations
TRANSLATION_DICT = {
    "平台": "Platform",
    "用户": "User",
    "支持": "Supports",
    "创建": "Create",
    "管理": "Manage",
    "配置": "Configuration",
    "模型": "Model",
    "知识库": "Knowledge Base",
    "工作流": "Workflow",
    "代理": "Agent",
    "服务": "Service", 
    "功能": "Feature",
    "应用": "Application",
    "数据": "Data",
    "接口": "Interface",
    "模块": "Module",
    "系统": "System",
    "企业级": "Enterprise-level",
    "安全": "Security",
    "高效": "Efficient",
    "合规": "Compliant",
    "解决方案": "Solution",
    "技术": "Technology",
    "开发": "Development",
    "工具": "Tools",
    "文档": "Documentation",
    "权限": "Permissions",
    "设置": "Settings",
    "参数": "Parameters",
    "结果": "Results",
    "状态": "Status",
    "流程": "Process",
    "部署": "Deployment",
    "测试": "Testing",
    "优化": "Optimization",
    "集成": "Integration",
    "分析": "Analysis",
    "监控": "Monitoring",
    "日志": "Logs",
    "错误": "Error",
    "警告": "Warning",
    "信息": "Information",
    "成功": "Success",
    "失败": "Failure",
    "开始": "Start",
    "结束": "End",
    "输入": "Input",
    "输出": "Output",
    "请求": "Request",
    "响应": "Response",
    "API": "API",
    "HTTP": "HTTP",
    "JSON": "JSON",
    "XML": "XML",
    "文本": "Text",
    "图像": "Image",
    "视频": "Video",
    "音频": "Audio",
    "文件": "File",
    "目录": "Directory",
    "路径": "Path",
    "链接": "Link",
    "地址": "Address",
    "网络": "Network",
    "数据库": "Database",
    "表": "Table",
    "索引": "Index",
    "查询": "Query",
    "记录": "Record",
    "字段": "Field",
    "类型": "Type",
    "格式": "Format",
    "编码": "Encoding",
    "解码": "Decoding",
    "加密": "Encryption",
    "解密": "Decryption",
    "认证": "Authentication",
    "授权": "Authorization",
    "权限": "Permission",
    "角色": "Role",
    "组": "Group",
    "组织": "Organization",
    "账户": "Account",
    "密码": "Password",
    "邮箱": "Email",
    "电话": "Phone",
    "姓名": "Name",
    "描述": "Description",
    "标题": "Title",
    "内容": "Content",
    "摘要": "Summary",
    "详情": "Details",
    "列表": "List",
    "页面": "Page",
    "导航": "Navigation",
    "菜单": "Menu",
    "按钮": "Button",
    "表单": "Form",
    "字段": "Field",
    "标签": "Label",
    "选项": "Option",
    "选择": "Select",
    "取消": "Cancel",
    "确认": "Confirm",
    "提交": "Submit",
    "重置": "Reset",
    "保存": "Save",
    "删除": "Delete",
    "编辑": "Edit",
    "复制": "Copy",
    "移动": "Move",
    "上传": "Upload",
    "下载": "Download",
    "导入": "Import",
    "导出": "Export",
    "搜索": "Search",
    "过滤": "Filter",
    "排序": "Sort",
    "分页": "Pagination",
    "总计": "Total",
    "统计": "Statistics",
    "报告": "Report",
    "图表": "Chart",
    "图形": "Graph",
    "仪表板": "Dashboard",
    "面板": "Panel",
    "组件": "Component",
    "库": "Library",
    "框架": "Framework",
    "插件": "Plugin",
    "扩展": "Extension",
    "主题": "Theme",
    "样式": "Style",
    "布局": "Layout",
    "模板": "Template",
    "脚本": "Script",
    "代码": "Code",
    "函数": "Function",
    "类": "Class",
    "对象": "Object",
    "属性": "Property",
    "方法": "Method",
    "事件": "Event",
    "回调": "Callback",
    "异常": "Exception",
    "处理": "Handling",
    "验证": "Validation",
    "转换": "Conversion",
    "序列化": "Serialization",
    "反序列化": "Deserialization",
    "缓存": "Cache",
    "会话": "Session",
    "队列": "Queue",
    "消息": "Message",
    "通知": "Notification",
    "提醒": "Reminder",
    "订阅": "Subscription",
    "发布": "Publish",
    "订阅": "Subscribe",
    "推送": "Push",
    "拉取": "Pull",
    "同步": "Synchronization",
    "异步": "Asynchronous",
    "并发": "Concurrency",
    "并行": "Parallelism",
    "分布式": "Distributed",
    "集群": "Cluster",
    "节点": "Node",
    "服务器": "Server",
    "客户端": "Client",
    "浏览器": "Browser",
    "移动端": "Mobile",
    "桌面端": "Desktop",
    "后台": "Backend",
    "前端": "Frontend",
    "全栈": "Full-stack",
    "中间件": "Middleware",
    "网关": "Gateway",
    "代理": "Proxy",
    "负载均衡": "Load Balancing",
    "容灾": "Disaster Recovery",
    "备份": "Backup",
    "恢复": "Recovery",
    "迁移": "Migration",
    "升级": "Upgrade",
    "更新": "Update",
    "补丁": "Patch",
    "版本": "Version",
    "发布": "Release",
    "部署": "Deploy",
    "环境": "Environment",
    "开发": "Development",
    "测试": "Testing",
    "生产": "Production",
    "运维": "Operations",
    "监控": "Monitoring",
    "日志": "Logging",
    "告警": "Alerting",
    "审计": "Audit",
    "合规": "Compliance",
    "治理": "Governance",
    "策略": "Policy",
    "规则": "Rule",
    "配置": "Configuration",
    "参数": "Parameter",
    "选项": "Option",
    "开关": "Switch",
    "标志": "Flag",
    "变量": "Variable",
    "常量": "Constant",
    "枚举": "Enumeration",
    "结构": "Structure",
    "接口": "Interface",
    "协议": "Protocol",
    "标准": "Standard",
    "规范": "Specification",
    "文档": "Documentation",
    "手册": "Manual",
    "指南": "Guide",
    "教程": "Tutorial",
    "示例": "Example",
    "演示": "Demo",
    "模板": "Template",
    "样例": "Sample",
    "参考": "Reference",
    "索引": "Index",
    "目录": "Table of Contents",
    "附录": "Appendix",
    "前言": "Preface",
    "后记": "Postscript",
    "致谢": "Acknowledgements",
    "版权": "Copyright",
    "许可": "License",
    "声明": "Statement",
    "注意事项": "Notes",
    "警告": "Warning",
    "提示": "Tip",
    "说明": "Description",
    "简介": "Introduction",
    "概述": "Overview",
    "摘要": "Abstract",
    "背景": "Background",
    "目标": "Objective",
    "范围": "Scope",
    "约束": "Constraint",
    "限制": "Limitation",
    "要求": "Requirement",
    "依赖": "Dependency",
    "前提": "Prerequisite",
    "条件": "Condition",
    "假设": "Assumption",
    "场景": "Scenario",
    "用例": "Use Case",
    "流程": "Process",
    "步骤": "Step",
    "操作": "Operation",
    "动作": "Action",
    "行为": "Behavior",
    "功能": "Function",
    "特性": "Feature",
    "优点": "Advantage",
    "缺点": "Disadvantage",
    "问题": "Problem",
    "解决方案": "Solution",
    "实现": "Implementation",
    "方法": "Method",
    "方式": "Way",
    "途径": "Approach",
    "技术": "Technology",
    "架构": "Architecture",
    "设计": "Design",
    "模式": "Pattern",
    "最佳实践": "Best Practice",
    "经验": "Experience",
    "教训": "Lesson",
    "总结": "Summary",
    "结论": "Conclusion",
    "展望": "Outlook",
    "趋势": "Trend",
    "发展": "Development",
    "进步": "Progress",
    "创新": "Innovation",
    "突破": "Breakthrough",
    "挑战": "Challenge",
    "机遇": "Opportunity",
    "风险": "Risk",
    "威胁": "Threat",
    "安全": "Security",
    "隐私": "Privacy",
    "保护": "Protection",
    "防范": "Prevention",
    "检测": "Detection",
    "响应": "Response",
    "恢复": "Recovery",
    "缓解": "Mitigation",
    "接受": "Acceptance",
    "转移": "Transfer",
    "避免": "Avoidance",
    "控制": "Control",
    "管理": "Management",
    "治理": "Governance",
    "监督": "Supervision",
    "检查": "Inspection",
    "审核": "Audit",
    "评估": "Evaluation",
    "分析": "Analysis",
    "研究": "Research",
    "调查": "Survey",
    "统计": "Statistics",
    "计算": "Calculation",
    "算法": "Algorithm",
    "公式": "Formula",
    "模型": "Model",
    "预测": "Prediction",
    "推断": "Inference",
    "学习": "Learning",
    "训练": "Training",
    "优化": "Optimization",
    "调优": "Tuning",
    "调试": "Debugging",
    "测试": "Testing",
    "验证": "Validation",
    "确认": "Confirmation",
    "演示": "Demonstration",
    "展示": "Showcase",
    "展览": "Exhibition",
    "会议": "Conference",
    "研讨会": "Seminar",
    "培训": "Training",
    "教育": "Education",
    "学习": "Learning",
    "知识": "Knowledge",
    "技能": "Skill",
    "能力": "Capability",
    "资质": "Qualification",
    "证书": "Certificate",
    "认证": "Certification",
    "授权": "Authorization",
    "许可": "License",
    "批准": "Approval",
    "同意": "Agreement",
    "合同": "Contract",
    "协议": "Agreement",
    "条款": "Terms",
    "条件": "Conditions",
    "要求": "Requirements",
    "规范": "Specifications",
    "标准": "Standards",
    "指南": "Guidelines",
    "流程": "Procedures",
    "程序": "Programs",
    "脚本": "Scripts",
    "代码": "Code",
    "函数": "Functions",
    "类": "Classes",
    "对象": "Objects",
    "数据": "Data",
    "信息": "Information",
    "内容": "Content",
    "媒体": "Media",
    "格式": "Formats",
    "编码": "Encoding",
    "解码": "Decoding",
    "压缩": "Compression",
    "解压": "Decompression",
    "打包": "Packaging",
    "分发": "Distribution",
    "安装": "Installation",
    "配置": "Configuration",
    "设置": "Settings",
    "选项": "Options",
    "参数": "Parameters",
    "默认": "Default",
    "高级": "Advanced",
    "基本": "Basic",
    "简单": "Simple",
    "复杂": "Complex",
    "困难": "Difficult",
    "容易": "Easy",
    "快速": "Fast",
    "缓慢": "Slow",
    "大小": "Size",
    "长度": "Length",
    "宽度": "Width",
    "高度": "Height",
    "深度": "Depth",
    "范围": "Range",
    "区域": "Area",
    "位置": "Position",
    "坐标": "Coordinates",
    "方向": "Direction",
    "路径": "Path",
    "路线": "Route",
    "距离": "Distance",
    "时间": "Time",
    "日期": "Date",
    "年": "Year",
    "月": "Month",
    "日": "Day",
    "时": "Hour",
    "分": "Minute",
    "秒": "Second",
    "毫秒": "Millisecond",
    "微秒": "Microsecond",
    "纳秒": "Nanosecond",
    "频率": "Frequency",
    "周期": "Period",
    "间隔": "Interval",
    "延迟": "Delay",
    "超时": "Timeout",
    "截止": "Deadline",
    "期限": "Time Limit",
    "计划": "Plan",
    "进度": "Progress",
    "状态": "Status",
    "阶段": "Phase",
    "里程碑": "Milestone",
    "目标": "Goal",
    "目的": "Purpose",
    "宗旨": "Mission",
    "愿景": "Vision",
    "战略": "Strategy",
    "战术": "Tactics",
    "方案": "Solution",
    "计划": "Plan",
    "方案": "Proposal",
    "建议": "Recommendation",
    "意见": "Opinion",
    "观点": "Viewpoint",
    "立场": "Position",
    "态度": "Attitude",
    "政策": "Policy",
    "规则": "Rules",
    "法规": "Regulations",
    "法律": "Law",
    "合法": "Legal",
    "非法": "Illegal",
    "合规": "Compliant",
    "违规": "Violation",
    "风险": "Risk",
    "评估": "Assessment",
    "分析": "Analysis",
    "监控": "Monitoring",
    "审计": "Audit",
    "检查": "Inspection",
    "审核": "Review",
    "批准": "Approval",
    "拒绝": "Rejection",
    "接受": "Acceptance",
    "完成": "Completion",
    "成功": "Success",
    "失败": "Failure",
    "错误": "Error",
    "异常": "Exception",
    "警告": "Warning",
    "提示": "Tip",
    "通知": "Notification",
    "消息": "Message",
    "信息": "Information",
    "数据": "Data",
    "记录": "Record",
    "日志": "Log",
    "文件": "File",
    "文档": "Document",
    "报告": "Report",
    "总结": "Summary",
    "详情": "Details",
    "描述": "Description",
    "说明": "Explanation",
    "解释": "Interpretation",
    "定义": "Definition",
    "概念": "Concept",
    "原理": "Principle",
    "机制": "Mechanism",
    "流程": "Process",
    "流程图": "Flowchart",
    "图表": "Chart",
    "图形": "Graph",
    "图像": "Image",
    "图片": "Picture",
    "照片": "Photo",
    "截图": "Screenshot",
    "演示": "Demo",
    "示例": "Example",
    "用例": "Use Case",
    "场景": "Scenario",
    "情况": "Situation",
    "状态": "State",
    "条件": "Condition",
    "环境": "Environment",
    "上下文": "Context",
    "背景": "Background",
    "历史": "History",
    "记录": "Record",
    "档案": "Archive",
    "存档": "Archive",
    "备份": "Backup",
    "恢复": "Restore",
    "还原": "Revert",
    "撤销": "Undo",
    "重做": "Redo",
    "复制": "Copy",
    "粘贴": "Paste",
    "剪切": "Cut",
    "删除": "Delete",
    "移除": "Remove",
    "添加": "Add",
    "插入": "Insert",
    "编辑": "Edit",
    "修改": "Modify",
    "更新": "Update",
    "替换": "Replace",
    "交换": "Swap",
    "移动": "Move",
    "拖动": "Drag",
    "放置": "Drop",
    "点击": "Click",
    "双击": "Double-click",
    "右击": "Right-click",
    "选择": "Select",
    "取消选择": "Deselect",
    "全选": "Select All",
    "清空": "Clear",
    "重置": "Reset",
    "刷新": "Refresh",
    "重新加载": "Reload",
    "加载": "Load",
    "卸载": "Unload",
    "安装": "Install",
    "卸载": "Uninstall",
    "配置": "Configure",
    "设置": "Set",
    "调整": "Adjust",
    "校准": "Calibrate",
    "优化": "Optimize",
    "调优": "Tune",
    "调试": "Debug",
    "测试": "Test",
    "验证": "Verify",
    "检查": "Check",
    "审核": "Audit",
    "评估": "Evaluate",
    "分析": "Analyze",
    "统计": "Statistics",
    "计算": "Calculate",
    "处理": "Process",
    "执行": "Execute",
    "运行": "Run",
    "启动": "Start",
    "停止": "Stop",
    "暂停": "Pause",
    "继续": "Continue",
    "完成": "Complete",
    "结束": "End",
    "退出": "Exit",
    "登录": "Login",
    "登出": "Logout",
    "注册": "Register",
    "注销": "Unregister",
    "订阅": "Subscribe",
    "取消订阅": "Unsubscribe",
    "关注": "Follow",
    "取消关注": "Unfollow",
    "喜欢": "Like",
    "不喜欢": "Dislike",
    "分享": "Share",
    "转发": "Forward",
    "回复": "Reply",
    "评论": "Comment",
    "评价": "Rate",
    "评分": "Rating",
    "投票": "Vote",
    "收藏": "Favorite",
    "书签": "Bookmark",
    "标签": "Tag",
    "分类": "Category",
    "分组": "Group",
    "排序": "Sort",
    "筛选": "Filter",
    "搜索": "Search",
    "查找": "Find",
    "替换": "Replace",
    "导航": "Navigate",
    "浏览": "Browse",
    "浏览": "Explore",
    "发现": "Discover",
    "推荐": "Recommend",
    "建议": "Suggest",
    "提示": "Hint",
    "帮助": "Help",
    "支持": "Support",
    "服务": "Service",
    "客户": "Customer",
    "用户": "User",
    "会员": "Member",
    "访问者": "Visitor",
    "管理员": "Administrator",
    "操作员": "Operator",
    "开发者": "Developer",
    "设计师": "Designer",
    "经理": "Manager",
    "主管": "Supervisor",
    "主任": "Director",
    "首席执行官": "CEO",
    "首席技术官": "CTO",
    "首席运营官": "COO",
    "首席财务官": "CFO",
    "员工": "Employee",
    "同事": "Colleague",
    "团队": "Team",
    "组织": "Organization",
    "公司": "Company",
    "企业": "Enterprise",
    "机构": "Institution",
    "部门": "Department",
    "单位": "Unit",
    "分支机构": "Branch",
    "办事处": "Office",
    "总部": "Headquarters",
    "分部": "Division",
    "子公司": "Subsidiary",
    "合作伙伴": "Partner",
    "供应商": "Supplier",
    "承包商": "Contractor",
    "顾问": "Consultant",
    "代理": "Agent",
    "经销商": "Distributor",
    "零售商": "Retailer",
    "批发商": "Wholesaler",
    "客户": "Client",
    "消费者": "Consumer",
    "市场": "Market",
    "行业": "Industry",
    "领域": "Field",
    "专业": "Professional",
    "专家": "Expert",
    "专门": "Specialized",
    "通用": "General",
    "普通": "Common",
    "标准": "Standard",
    "规格": "Specification",
    "要求": "Requirement",
    "需求": "Demand",
    "供应": "Supply",
    "库存": "Inventory",
    "库存": "Stock",
    "仓库": "Warehouse",
    "存储": "Storage",
    "容量": "Capacity",
    "空间": "Space",
    "内存": "Memory",
    "磁盘": "Disk",
    "硬盘": "Hard Drive",
    "固态硬盘": "SSD",
    "U盘": "USB Drive",
    "光盘": "Optical Disc",
    "磁带": "Tape",
    "网络": "Network",
    "互联网": "Internet",
    "局域网": "LAN",
    "广域网": "WAN",
    "无线网": "Wireless",
    "有线网": "Wired",
    "带宽": "Bandwidth",
    "速度": "Speed",
    "延迟": "Latency",
    "吞吐量": "Throughput",
    "协议": "Protocol",
    "标准": "Standard",
    "规范": "Specification",
    "接口": "Interface",
    "端口": "Port",
    "地址": "Address",
    "IP地址": "IP Address",
    "MAC地址": "MAC Address",
    "域名": "Domain Name",
    "URL": "URL",
    "链接": "Link",
    "连接": "Connection",
    "会话": "Session",
    "断开": "Disconnect",
    "重连": "Reconnect",
    "认证": "Authentication",
    "授权": "Authorization",
    "权限": "Permission",
    "访问": "Access",
    "控制": "Control",
    "管理": "Management",
    "配置": "Configuration",
    "设置": "Settings",
    "选项": "Options",
    "参数": "Parameters",
    "属性": "Properties",
    "特征": "Features",
    "功能": "Functions",
    "能力": "Capabilities",
    "性能": "Performance",
    "效率": "Efficiency",
    "效果": "Effectiveness",
    "质量": "Quality",
    "可靠性": "Reliability",
    "可用性": "Availability",
    "可扩展性": "Scalability",
    "可维护性": "Maintainability",
    "安全性": "Security",
    "隐私性": "Privacy",
    "兼容性": "Compatibility",
    "互操作性": "Interoperability",
    "可移植性": "Portability",
    "可重用性": "Reusability",
    "灵活性": "Flexibility",
    "适应性": "Adaptability",
    "稳定性": "Stability",
    "一致性": "Consistency",
    "完整性": "Integrity",
    "准确性": "Accuracy",
    "精确性": "Precision",
    "及时性": "Timeliness",
    "响应性": "Responsiveness",
    "用户体验": "User Experience",
    "界面": "Interface",
    "交互": "Interaction",
    "操作": "Operation",
    "导航": "Navigation",
    "菜单": "Menu",
    "工具栏": "Toolbar",
    "状态栏": "Status Bar",
    "滚动条": "Scrollbar",
    "按钮": "Button",
    "复选框": "Checkbox",
    "单选按钮": "Radio Button",
    "下拉列表": "Dropdown List",
    "列表框": "List Box",
    "文本框": "Text Box",
    "文本区域": "Text Area",
    "标签": "Label",
    "图像": "Image",
    "图标": "Icon",
    "链接": "Link",
    "表格": "Table",
    "图表": "Chart",
    "图形": "Graph",
    "地图": "Map",
    "视频": "Video",
    "音频": "Audio",
    "动画": "Animation",
    "媒体": "Media",
    "内容": "Content",
    "文本": "Text",
    "标题": "Title",
    "段落": "Paragraph",
    "列表": "List",
    "项目": "Item",
    "章节": "Chapter",
    "页": "Page",
    "文档": "Document",
    "文件": "File",
    "文件夹": "Folder",
    "目录": "Directory",
    "路径": "Path",
    "名称": "Name",
    "类型": "Type",
    "大小": "Size",
    "日期": "Date",
    "时间": "Time",
    "所有者": "Owner",
    "权限": "Permissions",
    "属性": "Attributes",
    "描述": "Description",
    "注释": "Comment",
    "备注": "Note",
    "标签": "Tag",
    "分类": "Category",
    "优先级": "Priority",
    "状态": "Status",
    "进度": "Progress",
    "阶段": "Phase",
    "里程碑": "Milestone",
    "截止日期": "Deadline",
    "开始日期": "Start Date",
    "结束日期": "End Date",
    "持续时间": "Duration",
    "工时": "Work Hours",
    "成本": "Cost",
    "预算": "Budget",
    "报价": "Quote",
    "发票": "Invoice",
    "收据": "Receipt",
    "账单": "Bill",
    "付款": "Payment",
    "收款": "Receipt",
    "转账": "Transfer",
    "汇款": "Remittance",
    "信用": "Credit",
    "借记": "Debit",
    "余额": "Balance",
    "账户": "Account",
    "银行": "Bank",
    "金融": "Finance",
    "投资": "Investment",
    "股票": "Stock",
    "债券": "Bond",
    "基金": "Fund",
    "保险": "Insurance",
    "贷款": "Loan",
    "抵押": "Mortgage",
    "利率": "Interest Rate",
    "汇率": "Exchange Rate",
    "税收": "Tax",
    "关税": "Tariff",
    "补贴": "Subsidy",
    "奖金": "Bonus",
    "佣金": "Commission",
    "费用": "Fee",
    "价格": "Price",
    "价值": "Value",
    "资产": "Asset",
    "负债": "Liability",
    "资本": "Capital",
    "收入": "Revenue",
    "支出": "Expense",
    "利润": "Profit",
    "亏损": "Loss",
    "收益": "Return",
    "回报": "Reward",
    "成本效益": "Cost-benefit",
    "投资回报率": "Return on Investment",
    "财务": "Financial",
    "会计": "Accounting",
    "审计": "Audit",
    "预算": "Budget",
    "预测": "Forecast",
    "规划": "Planning",
    "策略": "Strategy",
    "战术": "Tactics",
    "方案": "Plan",
    "计划": "Program",
    "项目": "Project",
    "任务": "Task",
    "活动": "Activity",
    "工作": "Work",
    "职位": "Position",
    "角色": "Role",
    "职责": "Responsibility",
    "义务": "Duty",
    "权力": "Authority",
    "决策": "Decision",
    "判断": "Judgment",
    "评估": "Assessment",
    "分析": "Analysis",
    "研究": "Research",
    "调查": "Survey",
    "报告": "Report",
    "总结": "Summary",
    "结论": "Conclusion",
    "建议": "Recommendation",
    "意见": "Opinion",
    "观点": "View",
    "立场": "Position",
    "态度": "Attitude",
    "信仰": "Belief",
    "价值观": "Values",
    "原则": "Principles",
    "标准": "Standards",
    "准则": "Guidelines",
    "规则": "Rules",
    "法规": "Regulations",
    "政策": "Policy",
    "法律": "Law",
    "合约": "Contract",
    "协议": "Agreement",
    "条款": "Terms",
    "条件": "Conditions",
    "要求": "Requirements",
    "规格": "Specifications",
    "标准": "Standards",
    "指南": "Guidelines",
    "手册": "Manual",
    "文档": "Documentation",
    "说明": "Instructions",
    "教程": "Tutorial",
    "培训": "Training",
    "课程": "Course",
    "学校": "School",
    "大学": "University",
    "学院": "College",
    "教育": "Education",
    "学习": "Learning",
    "研究": "Research",
    "开发": "Development",
    "创新": "Innovation",
    "发明": "Invention",
    "发现": "Discovery",
    "探索": "Exploration",
    "实验": "Experiment",
    "测试": "Test",
    "验证": "Validation",
    "检查": "Inspection",
    "审核": "Review",
    "批准": "Approval",
    "发布": "Release",
    "部署": "Deployment",
    "运行": "Operation",
    "维护": "Maintenance",
    "支持": "Support",
    "服务": "Service",
    "客户": "Customer",
    "用户": "User",
    "社区": "Community",
    "论坛": "Forum",
    "博客": "Blog",
    "新闻": "News",
    "文章": "Article",
    "出版物": "Publication",
    "期刊": "Journal",
    "杂志": "Magazine",
    "报纸": "Newspaper",
    "媒体": "Media",
    "广播": "Broadcast",
    "电视": "Television",
    "电台": "Radio",
    "网络": "Internet",
    "网站": "Website",
    "网页": "Webpage",
    "应用": "Application",
    "程序": "Program",
    "软件": "Software",
    "系统": "System",
    "平台": "Platform",
    "技术": "Technology",
    "工具": "Tools",
    "设备": "Equipment",
    "硬件": "Hardware",
    "机器": "Machine",
    "装置": "Device",
    "仪器": "Instrument",
    "组件": "Component",
    "部件": "Part",
    "零件": "Component",
    "配件": "Accessory",
    "附件": "Attachment",
    "模块": "Module",
    "单元": "Unit",
    "系统": "System",
    "网络": "Network",
    "连接": "Connection",
    "接口": "Interface",
    "端口": "Port",
    "插槽": "Slot",
    "插座": "Socket",
    "插头": "Plug",
    "线缆": "Cable",
    "电线": "Wire",
    "电缆": "Cable",
    "光纤": "Optical Fiber",
    "天线": "Antenna",
    "传感器": "Sensor",
    "执行器": "Actuator",
    "控制器": "Controller",
    "处理器": "Processor",
    "内存": "Memory",
    "存储": "Storage",
    "驱动器": "Drive",
    "显示器": "Display",
    "屏幕": "Screen",
    "键盘": "Keyboard",
    "鼠标": "Mouse",
    "触摸板": "Touchpad",
    "触摸屏": "Touchscreen",
    "摄像头": "Camera",
    "麦克风": "Microphone",
    "扬声器": "Speaker",
    "耳机": "Headphones",
    "打印机": "Printer",
    "扫描仪": "Scanner",
    "投影仪": "Projector",
    "路由器": "Router",
    "交换机": "Switch",
    "集线器": "Hub",
    "防火墙": "Firewall",
    "服务器": "Server",
    "工作站": "Workstation",
    "计算机": "Computer",
    "笔记本": "Laptop",
    "平板": "Tablet",
    "手机": "Phone",
    "智能设备": "Smart Device",
    "可穿戴设备": "Wearable Device",
    "物联网": "Internet of Things",
    "云计算": "Cloud Computing",
    "大数据": "Big Data",
    "人工智能": "Artificial Intelligence",
    "机器学习": "Machine Learning",
    "深度学习": "Deep Learning",
    "神经网络": "Neural Network",
    "算法": "Algorithm",
    "模型": "Model",
    "数据": "Data",
    "信息": "Information",
    "知识": "Knowledge",
    "智慧": "Wisdom",
    "智能": "Intelligence",
    "自动化": "Automation",
    "机器人": "Robot",
    "无人机": "Drone",
    "自动驾驶": "Autonomous Driving",
    "虚拟现实": "Virtual Reality",
    "增强现实": "Augmented Reality",
    "混合现实": "Mixed Reality",
    "区块链": "Blockchain",
    "加密货币": "Cryptocurrency",
    "数字货币": "Digital Currency",
    "电子支付": "Electronic Payment",
    "移动支付": "Mobile Payment",
    "在线支付": "Online Payment",
    "电子商务": "E-commerce",
    "电子政务": "E-government",
    "电子学习": "E-learning",
    "电子健康": "E-health",
    "电子银行": "E-banking",
    "电子图书": "E-book",
    "电子杂志": "E-magazine",
    "电子报纸": "E-newspaper",
    "电子音乐": "E-music",
    "电子游戏": "E-game",
    "数字内容": "Digital Content",
    "数字媒体": "Digital Media",
    "数字营销": "Digital Marketing",
    "数字广告": "Digital Advertising",
    "数字签名": "Digital Signature",
    "数字证书": "Digital Certificate",
    "数字身份": "Digital Identity",
    "数字钱包": "Digital Wallet",
    "数字转型": "Digital Transformation",
    "数字经济": "Digital Economy",
    "数字社会": "Digital Society",
    "数字城市": "Digital City",
    "数字乡村": "Digital Village",
    "数字政府": "Digital Government",
    "数字企业": "Digital Enterprise",
    "数字公民": "Digital Citizen",
    "数字素养": "Digital Literacy",
    "数字素养": "Digital Competence",
    "数字技能": "Digital Skills",
    "数字能力": "Digital Capabilities",
    "数字思维": "Digital Thinking",
    "数字文化": "Digital Culture",
    "数字生态": "Digital Ecosystem",
    "数字平台": "Digital Platform",
    "数字服务": "Digital Services",
    "数字产品": "Digital Products",
    "数字解决方案": "Digital Solutions",
    "数字化转型": "Digital Transformation",
    "数字化": "Digitalization",
    "信息化": "Informatization",
    "网络化": "Networked",
    "智能化": "Intelligentization",
    "自动化": "Automation",
    "现代化": "Modernization",
    "标准化": "Standardization",
    "规范化": "Normalization",
    "系统化": "Systematization",
    "集成化": "Integration",
    "一体化": "Integration",
    "综合化": "Comprehensiveness",
    "专业化": "Specialization",
    "精细化": "Refinement",
    "个性化": "Personalization",
    "定制化": "Customization",
    "多样化": "Diversification",
    "国际化": "Internationalization",
    "全球化": "Globalization",
    "本地化": "Localization",
    "区域化": "Regionalization",
    "城市化": "Urbanization",
    "工业化": "Industrialization",
    "现代化": "Modernization",
    "信息化": "Informatization",
    "数字化": "Digitalization",
    "智能化": "Intelligentization",
    "网络化": "Networked",
    "自动化": "Automation",
    "一体化": "Integration",
    "集成化": "Integration",
    "系统化": "Systematization",
    "标准化": "Standardization",
    "规范化": "Normalization",
    "专业化": "Specialization",
    "精细化": "Refinement",
    "个性化": "Personalization",
    "定制化": "Customization",
    "多样化": "Diversification",
    "模块化": "Modularization",
    "组件化": "Componentization",
    "平台化": "Platformization",
    "服务化": "Servicization",
    "产品化": "Productization",
    "商品化": "Commercialization",
    "市场化": "Marketization",
    "社会化": "Socialization",
    "生态化": "Ecologization",
    "绿色化": "Greening",
    "低碳化": "Low-carbon",
    "可持续发展": "Sustainable Development",
    "循环经济": "Circular Economy",
    "绿色经济": "Green Economy",
    "低碳经济": "Low-carbon Economy",
    "数字经济": "Digital Economy",
    "分享经济": "Sharing Economy",
    "平台经济": "Platform Economy",
    "生态经济": "Ecological Economy",
    "创新经济": "Innovation Economy",
    "知识经济": "Knowledge Economy",
    "体验经济": "Experience Economy",
    "注意力经济": "Attention Economy",
    "影响力经济": "Influence Economy",
    "数据经济": "Data Economy",
    "算法经济": "Algorithm Economy",
    "智能经济": "Intelligent Economy",
    "未来经济": "Future Economy",
}

def translate_chinese_to_english(text):
    """
    Simple translation function to translate common Chinese terms to English
    """
    # Split into lines for better context handling
    lines = text.split('\n')
    translated_lines = []
    
    for line in lines:
        # Skip lines that are already in English or don't contain Chinese
        if not re.search(r'[\u4e00-\u9fff]', line):
            translated_lines.append(line)
            continue
            
        # Handle common phrases and sentence structures first
        line = re.sub(r'可通过(.+)，(.+)', r'\1 can \2', line)
        line = re.sub(r'支持(.+)，(.+)', r'Supports \1, \2', line)
        line = re.sub(r'提供(.+)，(.+)', r'Provides \1, \2', line)
        line = re.sub(r'用于(.+)，(.+)', r'Used for \1, \2', line)
        line = re.sub(r'点击(.+)，(.+)', r'Click \1 to \2', line)
        line = re.sub(r'在(.+)中', r'in \1', line)
        line = re.sub(r'的(.+)', r'\1', line)
        line = re.sub(r'是(.+)的', r'is a \1', line)
        line = re.sub(r'为(.+)提供', r'provide \1 for', line)
        line = re.sub(r'用于(.+)', r'for \1', line)
        line = re.sub(r'可(.+)', r'can \1', line)
        line = re.sub(r'进行(.+)', r'perform \1', line)
        line = re.sub(r'使用(.+)', r'use \1', line)
        line = re.sub(r'包括(.+)', r'including \1', line)
        line = re.sub(r'以及(.+)', r'and \1', line)
        line = re.sub(r'或(.+)', r'or \1', line)
        line = re.sub(r'等(.+)', r'and other \1', line)
        
        # Then replace individual terms
        for chinese, english in TRANSLATION_DICT.items():
            line = line.replace(chinese, english)
        
        # Handle punctuation
        line = re.sub(r'[，。！？；：""''（）【】《》]', lambda m: {
            '，': ', ',
            '。': '. ',
            '！': '! ',
            '？': '? ',
            '；': '; ',
            '：': ': ',
            '"': '"',
            '"': '"',
            ''': "'",
            ''': "'",
            '（': '(',
            '）': ')',
            '【': '[',
            '】': ']',
            '《': '"',
            '》': '"'
        }.get(m.group(0), m.group(0)), line)
        
        # Clean up spaces around punctuation
        line = re.sub(r'\s*([,.!?;:])\s*', r'\1 ', line)
        line = re.sub(r'\s+', ' ', line)
        
        translated_lines.append(line.strip())
    
    # Rejoin and fix markdown formatting
    result = '\n'.join(translated_lines)
    
    # Fix headers
    result = re.sub(r'^#+\s*([^\n]+)\s*$', lambda m: '#' * len(m.group(0).split()[0]) + ' ' + m.group(1), result, flags=re.MULTILINE)
    
    # Fix numbered lists
    result = re.sub(r'^(\d+)\)\s+', r'\1. ', result, flags=re.MULTILINE)
    
    # Fix spacing around headers
    result = re.sub(r'\n(#+\s+[^\n]+)\n', r'\n\1\n\n', result)
    
    return result.strip()

def translate_markdown_file(file_path):
    """
    Translate a markdown file from Chinese to English
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Only translate if content contains Chinese characters
        if re.search(r'[\u4e00-\u9fff]', content):
            translated_content = translate_chinese_to_english(content)
            
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(translated_content)
            
            print(f"Translated: {file_path}")
            return True
        else:
            print(f"No Chinese content found in: {file_path}")
            return False
            
    except Exception as e:
        print(f"Error translating {file_path}: {e}")
        return False

def main():
    """
    Main function to translate all markdown files
    """
    manual_en_dir = "/Users/mohankumarv/Desktop/SAFVR/wanwu/configs/microservice/bff-service/static/Manual_en"
    
    # Find all markdown files recursively
    md_files = glob.glob(f"{manual_en_dir}/**/*.md", recursive=True)
    
    print(f"Found {len(md_files)} markdown files to translate")
    
    translated_count = 0
    for md_file in md_files:
        if translate_markdown_file(md_file):
            translated_count += 1
    
    print(f"Translation complete! Translated {translated_count} files.")

if __name__ == "__main__":
    main()
