recommend_models:
  - provider: "HuoShan"
    llm:
      - model: "doubao-seed-evolving"
        display_name: "doubao-seed-evolving"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "doubao-seed-2-1-pro-260628"
        display_name: "doubao-seed-2-1-pro-260628"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "doubao-seed-2-1-turbo-260628"
        display_name: "doubao-seed-2-1-turbo-260628"
        tags: ["图文问答","深度思考开关","工具调用"]
    sync-asr:
      - model: "volc.bigasr.auc_turbo"
        display_name: "大模型录音文件极速版"

  - provider: "YuanJing"
    llm:
      - model: "deepseek-v4-pro-0813"
        display_name: "deepseek-v4-pro-0813"
        tags: ["深度思考开关","工具调用"]
      - model: "qwen3.8-27b"
        display_name: "qwen3.8-27b"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "glm-5"
        display_name: "glm-5"
        tags: ["深度思考开关","工具调用"]
      - model: "YuanjingVL"
        display_name: "YuanjingVL"
        tags: ["图文问答"]
    rerank:
      - model: "qwen3-reranker-0.6b"
        display_name: "qwen3-reranker-0.6b"
      - model: "qwen3-reranker-4b"
        display_name: "qwen3-reranker-4b"
    multimodal-rerank:
      - model: "qwen3-vl-reranker-2b"
        display_name: "qwen3-vl-reranker-2b"
      - model: "qwen3-vl-reranker-8b"
        display_name: "qwen3-vl-reranker-8b"
    embedding:
      - model: "qwen3-embed-0.6b"
        display_name: "qwen3-embed-0.6b"
    multimodal-embedding:
      - model: "qwen3-vl-embedding-2b"
        display_name: "qwen3-vl-embedding-2b"
      - model: "qwen3-vl-embedding-8b"
        display_name: "qwen3-vl-embedding-8b"
    gui:
      - model: "gui_agent_v1"
        display_name: "gui_agent_v1"
    ocr:
      - model: "pdf-parser"
        display_name: "OCR-高精度"
        support_filetypes: ["pdf", "png", "jpg", "jpeg"]
#    sync-asr:
#      - model: "yuanjing-asr"
#        display_name: "yuanjing-asr"
#    pdf-parser:
#      - model: "pdf-parser"
#        display_name: "知识库-高精度文档解析工具"


  - provider: "Qwen"
    llm:
      - model: "qwen3.8-max"
        display_name: "qwen3.8-max"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "qwen3.7-plus"
        display_name: "qwen3.7-plus"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "qwen3-vl-plus"
        display_name: "qwen3-vl-plus"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "qwen3.7-flash"
        display_name: "qwen3.7-flash"
        tags: ["图文问答","深度思考开关","工具调用"]
    rerank:
      - model: "gte-rerank-v2"
        display_name: "gte-rerank-v2"
    multimodal-rerank:
      - model: "qwen3-vl-rerank"
        display_name: "qwen3-vl-rerank"
    embedding:
      - model: "qwen3.7-text-embedding"
        display_name: "qwen3.7-text-embedding"
    multimodal-embedding:
      - model: "tongyi-embedding-vision-flash-2026-03-06"
        display_name: "tongyi-embedding-vision-flash-2026-03-06"
    sync-asr:
      - model: "qwen3-asr-flash"
        display_name: "qwen3-asr-flash"

  - provider: "Infini"
    llm:
      - model: "kimi-k2.5"
        display_name: "kimi-k2.5"
        tags: ["图文问答","深度思考开关","工具调用"]
      - model: "glm-4.5v"
        display_name: "glm-4.5v"
        tags: ["图文问答","深度思考开关"]
      - model: "glm-5"
        display_name: "glm-5"
        tags: ["深度思考开关","工具调用"]
      - model: "deepseek-v3.2"
        display_name: "deepseek-v3.2"
        tags: ["深度思考开关","工具调用"]
    rerank:
      - model: "bge-reranker-v2-m3"
        display_name: "bge-reranker-v2-m3"
    embedding:
      - model: "jina-embeddings-v2-base-code"
        display_name: "jina-embeddings-v2-base-code"
      - model: "jina-embeddings-v2-base-zh"
        display_name: "jina-embeddings-v2-base-zh"
      - model: "bge-m3"
        display_name: "BAAI/bge-m3"

  - provider: "QianFan"
    llm:
      - model: "ernie-5.0"
        display_name: "ERNIE 5.0"
        tags: ["图文问答","深度思考开关", "工具调用"]
      - model: "ernie-5.1"
        display_name: "ernie-5.1"
        tags: ["工具调用","深度思考开关"]
      - model: "ernie-x1.1"
        display_name: "ERNIE X1.1"
        tags: ["深度思考开关", "工具调用"]
    rerank:
      - model: "bce-reranker-base"
        display_name: "bce-reranker-base"
    embedding:
      - model: "qwen3-embedding-8b"
        display_name: "qwen3-embedding-8b"
    ocr:
      - model: "paddleocr-vl-0.9b"
        display_name: "paddleocr-vl-0.9b"
        support_filetypes: ["pdf", "png", "jpg", "jpeg"]

  - provider: "ZhiPu"
    llm:
      - model: "glm-5"
        display_name: "glm-5"
        tags: [ "深度思考开关", "工具调用" ]
      - model: "glm-5.1"
        display_name: "glm-5.1"
        tags: [ "深度思考开关", "工具调用" ]
      - model: "glm-5.2"
        display_name: "glm-5.2"
        tags: [ "深度思考开关", "工具调用" ]
      - model: "glm-5v-turbo"
        display_name: "glm-5v-turbo"
        tags: [ "图文问答","深度思考开关", "工具调用" ]
    rerank:
      - model: "rerank"
        display_name: "智谱 rerank"
    embedding:
      - model: "embedding-3"
        display_name: "embedding-3"

  - provider: "DeepSeek"
    llm:
      - model: "deepseek-v4-flash"
        display_name: "deepseek-v4-flash"
        tags: ["深度思考开关", "工具调用"]
      - model: "deepseek-v4-pro"
        display_name: "deepseek-v4-pro"
        tags: ["深度思考开关", "工具调用"]
      - model: "deepseek-v4-flash-vision-exp"
        display_name: "deepseek-v4-flash-vision-exp"
        tags: [ "图文问答","深度思考开关", "工具调用" ]

  - provider: "Jina"
    rerank:
      - model: "jina-reranker-v2-base-multilingual"
        display_name: "jina-reranker-v2-base-multilingual"
      - model: "jina-reranker-v3"
        display_name: "jina-reranker-v3"
    multimodal-rerank:
      - model: "jina-reranker-m0"
        display_name: "jina-reranker-m0"
    embedding:
      - model: "jina-embeddings-v3"
        display_name: "jina-embeddings-v3"
      - model: "jina-embeddings-v5-text-small"
        display_name: "jina-embeddings-v5-text-small"
    multimodal-embedding:
      - model: "jina-embeddings-v4"
        display_name: "jina-embeddings-v4"
      - model: "jina-clip-v2"
        display_name: "jina-clip-v2"

  - provider: "Ollama"
    llm:
      - model: "glm-5:cloud"
        display_name: "glm-5:cloud"
        tags: [ "深度思考开关", "工具调用" ]
    embedding:
      - model: "granite-embedding:latest"
        display_name: "granite-embedding:latest"

  - provider: "OpenAI-API-compatible"
    llm:
      - model: "glm-5"
        display_name: "glm-5"
        tags: [ "深度思考开关", "工具调用" ]
    rerank:
      - model: "qwen3-reranker-4b"
        display_name: "qwen3-reranker-4b"
    embedding:
      - model: "qwen3-embed-0.6b"
        display_name: "qwen3-embed-0.6b"
    sync-asr:
      - model: "Qwen3-ASR-1.7B"
        display_name: "Qwen3-ASR-1.7B"