// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/rag-service/rag-service.proto

package rag_service

import (
	context "context"
	common "github.com/UnicomAI/wanwu/api/proto/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RagService_ChatRag_FullMethodName                    = "/rag_service.RagService/ChatRag"
	RagService_CreateRag_FullMethodName                  = "/rag_service.RagService/CreateRag"
	RagService_UpdateRag_FullMethodName                  = "/rag_service.RagService/UpdateRag"
	RagService_UpdateRagConfig_FullMethodName            = "/rag_service.RagService/UpdateRagConfig"
	RagService_DeleteRag_FullMethodName                  = "/rag_service.RagService/DeleteRag"
	RagService_GetRagDetail_FullMethodName               = "/rag_service.RagService/GetRagDetail"
	RagService_ListRag_FullMethodName                    = "/rag_service.RagService/ListRag"
	RagService_AdminRagPageList_FullMethodName           = "/rag_service.RagService/AdminRagPageList"
	RagService_GetRagByIds_FullMethodName                = "/rag_service.RagService/GetRagByIds"
	RagService_CopyRag_FullMethodName                    = "/rag_service.RagService/CopyRag"
	RagService_PublishRag_FullMethodName                 = "/rag_service.RagService/PublishRag"
	RagService_UpdatePublishRag_FullMethodName           = "/rag_service.RagService/UpdatePublishRag"
	RagService_ListPublishRagHistory_FullMethodName      = "/rag_service.RagService/ListPublishRagHistory"
	RagService_OverwriteRagDraft_FullMethodName          = "/rag_service.RagService/OverwriteRagDraft"
	RagService_GetPublishRagDesc_FullMethodName          = "/rag_service.RagService/GetPublishRagDesc"
	RagService_GetPublishRagDescBatch_FullMethodName     = "/rag_service.RagService/GetPublishRagDescBatch"
	RagService_CreateRagConversation_FullMethodName      = "/rag_service.RagService/CreateRagConversation"
	RagService_DeleteRagConversation_FullMethodName      = "/rag_service.RagService/DeleteRagConversation"
	RagService_ListRagConversation_FullMethodName        = "/rag_service.RagService/ListRagConversation"
	RagService_ListRagConversationDetail_FullMethodName  = "/rag_service.RagService/ListRagConversationDetail"
	RagService_ClearRagConversationDetail_FullMethodName = "/rag_service.RagService/ClearRagConversationDetail"
	RagService_GetRagDraftConversation_FullMethodName    = "/rag_service.RagService/GetRagDraftConversation"
	RagService_GetRagConversationOwner_FullMethodName    = "/rag_service.RagService/GetRagConversationOwner"
	RagService_RagMessageFeedback_FullMethodName         = "/rag_service.RagService/RagMessageFeedback"
	RagService_GetConversationLog_FullMethodName         = "/rag_service.RagService/GetConversationLog"
)

// RagServiceClient is the client API for RagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RagServiceClient interface {
	// 流式对话
	ChatRag(ctx context.Context, in *ChatRagReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatRagResp], error)
	// 创建 rag
	CreateRag(ctx context.Context, in *CreateRagReq, opts ...grpc.CallOption) (*CreateRagResp, error)
	// 更新 rag 基本信息
	UpdateRag(ctx context.Context, in *UpdateRagReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 更新 rag 配置信息
	UpdateRagConfig(ctx context.Context, in *UpdateRagConfigReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除 rag
	DeleteRag(ctx context.Context, in *RagDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 获取 rag
	GetRagDetail(ctx context.Context, in *RagDetailReq, opts ...grpc.CallOption) (*RagInfo, error)
	// 获取 rag 列表
	ListRag(ctx context.Context, in *RagListReq, opts ...grpc.CallOption) (*RagListResp, error)
	// 管理员中心知识问答全局分页列表（跨用户/组织）
	AdminRagPageList(ctx context.Context, in *AdminRagPageListReq, opts ...grpc.CallOption) (*AdminRagPageListResp, error)
	// 根据 ragIds 获取 rag 列表
	GetRagByIds(ctx context.Context, in *GetRagByIdsReq, opts ...grpc.CallOption) (*AppBriefList, error)
	// 复制 rag
	CopyRag(ctx context.Context, in *CopyRagReq, opts ...grpc.CallOption) (*CreateRagResp, error)
	// 发布 rag
	PublishRag(ctx context.Context, in *PublishRagReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 编辑发布后rag的版本描述
	UpdatePublishRag(ctx context.Context, in *UpdatePublishRagReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 历史版本列表
	ListPublishRagHistory(ctx context.Context, in *ListPublishRagHistoryReq, opts ...grpc.CallOption) (*ListPublishRagHistoryResp, error)
	// 覆盖当前草稿
	OverwriteRagDraft(ctx context.Context, in *OverwriteRagDraftReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 返回最新版本描述
	GetPublishRagDesc(ctx context.Context, in *GetPublishRagDescReq, opts ...grpc.CallOption) (*GetPublishRagDescResp, error)
	// 批量返回最新版本描述
	GetPublishRagDescBatch(ctx context.Context, in *GetPublishRagDescBatchReq, opts ...grpc.CallOption) (*GetPublishRagDescBatchResp, error)
	// --- 会话 ---
	// 创建会话
	CreateRagConversation(ctx context.Context, in *CreateRagConversationReq, opts ...grpc.CallOption) (*CreateRagConversationResp, error)
	// 删除会话，连带清除该会话下的问答明细
	DeleteRagConversation(ctx context.Context, in *DeleteRagConversationReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 会话列表
	ListRagConversation(ctx context.Context, in *ListRagConversationReq, opts ...grpc.CallOption) (*ListRagConversationResp, error)
	// 会话下的问答明细列表
	ListRagConversationDetail(ctx context.Context, in *ListRagConversationDetailReq, opts ...grpc.CallOption) (*ListRagConversationDetailResp, error)
	// 清除问答明细但保留会话，detailId 传值则只删单条
	ClearRagConversationDetail(ctx context.Context, in *ClearRagConversationDetailReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 取草稿会话id，草稿态每个知识问答仅维护一条会话
	GetRagDraftConversation(ctx context.Context, in *GetRagDraftConversationReq, opts ...grpc.CallOption) (*GetRagDraftConversationResp, error)
	// 取会话归属信息，供 bff 中间件校验（明细在 ES，bff 查不到，一并在这里判）
	GetRagConversationOwner(ctx context.Context, in *GetRagConversationOwnerReq, opts ...grpc.CallOption) (*GetRagConversationOwnerResp, error)
	// 问答明细点赞/点踩
	RagMessageFeedback(ctx context.Context, in *RagMessageFeedbackReq, opts ...grpc.CallOption) (*RagMessageFeedbackResp, error)
	// --- 会话日志 ---
	GetConversationLog(ctx context.Context, in *ConversationLogReq, opts ...grpc.CallOption) (*common.ConversationLog, error)
}

type ragServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRagServiceClient(cc grpc.ClientConnInterface) RagServiceClient {
	return &ragServiceClient{cc}
}

func (c *ragServiceClient) ChatRag(ctx context.Context, in *ChatRagReq, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatRagResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RagService_ServiceDesc.Streams[0], RagService_ChatRag_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRagReq, ChatRagResp]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RagService_ChatRagClient = grpc.ServerStreamingClient[ChatRagResp]

func (c *ragServiceClient) CreateRag(ctx context.Context, in *CreateRagReq, opts ...grpc.CallOption) (*CreateRagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRagResp)
	err := c.cc.Invoke(ctx, RagService_CreateRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) UpdateRag(ctx context.Context, in *UpdateRagReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_UpdateRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) UpdateRagConfig(ctx context.Context, in *UpdateRagConfigReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_UpdateRagConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteRag(ctx context.Context, in *RagDeleteReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_DeleteRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetRagDetail(ctx context.Context, in *RagDetailReq, opts ...grpc.CallOption) (*RagInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagInfo)
	err := c.cc.Invoke(ctx, RagService_GetRagDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ListRag(ctx context.Context, in *RagListReq, opts ...grpc.CallOption) (*RagListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagListResp)
	err := c.cc.Invoke(ctx, RagService_ListRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) AdminRagPageList(ctx context.Context, in *AdminRagPageListReq, opts ...grpc.CallOption) (*AdminRagPageListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdminRagPageListResp)
	err := c.cc.Invoke(ctx, RagService_AdminRagPageList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetRagByIds(ctx context.Context, in *GetRagByIdsReq, opts ...grpc.CallOption) (*AppBriefList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppBriefList)
	err := c.cc.Invoke(ctx, RagService_GetRagByIds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) CopyRag(ctx context.Context, in *CopyRagReq, opts ...grpc.CallOption) (*CreateRagResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRagResp)
	err := c.cc.Invoke(ctx, RagService_CopyRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) PublishRag(ctx context.Context, in *PublishRagReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_PublishRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) UpdatePublishRag(ctx context.Context, in *UpdatePublishRagReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_UpdatePublishRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ListPublishRagHistory(ctx context.Context, in *ListPublishRagHistoryReq, opts ...grpc.CallOption) (*ListPublishRagHistoryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishRagHistoryResp)
	err := c.cc.Invoke(ctx, RagService_ListPublishRagHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) OverwriteRagDraft(ctx context.Context, in *OverwriteRagDraftReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_OverwriteRagDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetPublishRagDesc(ctx context.Context, in *GetPublishRagDescReq, opts ...grpc.CallOption) (*GetPublishRagDescResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishRagDescResp)
	err := c.cc.Invoke(ctx, RagService_GetPublishRagDesc_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetPublishRagDescBatch(ctx context.Context, in *GetPublishRagDescBatchReq, opts ...grpc.CallOption) (*GetPublishRagDescBatchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishRagDescBatchResp)
	err := c.cc.Invoke(ctx, RagService_GetPublishRagDescBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) CreateRagConversation(ctx context.Context, in *CreateRagConversationReq, opts ...grpc.CallOption) (*CreateRagConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRagConversationResp)
	err := c.cc.Invoke(ctx, RagService_CreateRagConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) DeleteRagConversation(ctx context.Context, in *DeleteRagConversationReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_DeleteRagConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ListRagConversation(ctx context.Context, in *ListRagConversationReq, opts ...grpc.CallOption) (*ListRagConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRagConversationResp)
	err := c.cc.Invoke(ctx, RagService_ListRagConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ListRagConversationDetail(ctx context.Context, in *ListRagConversationDetailReq, opts ...grpc.CallOption) (*ListRagConversationDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRagConversationDetailResp)
	err := c.cc.Invoke(ctx, RagService_ListRagConversationDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) ClearRagConversationDetail(ctx context.Context, in *ClearRagConversationDetailReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, RagService_ClearRagConversationDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetRagDraftConversation(ctx context.Context, in *GetRagDraftConversationReq, opts ...grpc.CallOption) (*GetRagDraftConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRagDraftConversationResp)
	err := c.cc.Invoke(ctx, RagService_GetRagDraftConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetRagConversationOwner(ctx context.Context, in *GetRagConversationOwnerReq, opts ...grpc.CallOption) (*GetRagConversationOwnerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRagConversationOwnerResp)
	err := c.cc.Invoke(ctx, RagService_GetRagConversationOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) RagMessageFeedback(ctx context.Context, in *RagMessageFeedbackReq, opts ...grpc.CallOption) (*RagMessageFeedbackResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RagMessageFeedbackResp)
	err := c.cc.Invoke(ctx, RagService_RagMessageFeedback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragServiceClient) GetConversationLog(ctx context.Context, in *ConversationLogReq, opts ...grpc.CallOption) (*common.ConversationLog, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(common.ConversationLog)
	err := c.cc.Invoke(ctx, RagService_GetConversationLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServiceServer is the server API for RagService service.
// All implementations must embed UnimplementedRagServiceServer
// for forward compatibility.
type RagServiceServer interface {
	// 流式对话
	ChatRag(*ChatRagReq, grpc.ServerStreamingServer[ChatRagResp]) error
	// 创建 rag
	CreateRag(context.Context, *CreateRagReq) (*CreateRagResp, error)
	// 更新 rag 基本信息
	UpdateRag(context.Context, *UpdateRagReq) (*emptypb.Empty, error)
	// 更新 rag 配置信息
	UpdateRagConfig(context.Context, *UpdateRagConfigReq) (*emptypb.Empty, error)
	// 删除 rag
	DeleteRag(context.Context, *RagDeleteReq) (*emptypb.Empty, error)
	// 获取 rag
	GetRagDetail(context.Context, *RagDetailReq) (*RagInfo, error)
	// 获取 rag 列表
	ListRag(context.Context, *RagListReq) (*RagListResp, error)
	// 管理员中心知识问答全局分页列表（跨用户/组织）
	AdminRagPageList(context.Context, *AdminRagPageListReq) (*AdminRagPageListResp, error)
	// 根据 ragIds 获取 rag 列表
	GetRagByIds(context.Context, *GetRagByIdsReq) (*AppBriefList, error)
	// 复制 rag
	CopyRag(context.Context, *CopyRagReq) (*CreateRagResp, error)
	// 发布 rag
	PublishRag(context.Context, *PublishRagReq) (*emptypb.Empty, error)
	// 编辑发布后rag的版本描述
	UpdatePublishRag(context.Context, *UpdatePublishRagReq) (*emptypb.Empty, error)
	// 历史版本列表
	ListPublishRagHistory(context.Context, *ListPublishRagHistoryReq) (*ListPublishRagHistoryResp, error)
	// 覆盖当前草稿
	OverwriteRagDraft(context.Context, *OverwriteRagDraftReq) (*emptypb.Empty, error)
	// 返回最新版本描述
	GetPublishRagDesc(context.Context, *GetPublishRagDescReq) (*GetPublishRagDescResp, error)
	// 批量返回最新版本描述
	GetPublishRagDescBatch(context.Context, *GetPublishRagDescBatchReq) (*GetPublishRagDescBatchResp, error)
	// --- 会话 ---
	// 创建会话
	CreateRagConversation(context.Context, *CreateRagConversationReq) (*CreateRagConversationResp, error)
	// 删除会话，连带清除该会话下的问答明细
	DeleteRagConversation(context.Context, *DeleteRagConversationReq) (*emptypb.Empty, error)
	// 会话列表
	ListRagConversation(context.Context, *ListRagConversationReq) (*ListRagConversationResp, error)
	// 会话下的问答明细列表
	ListRagConversationDetail(context.Context, *ListRagConversationDetailReq) (*ListRagConversationDetailResp, error)
	// 清除问答明细但保留会话，detailId 传值则只删单条
	ClearRagConversationDetail(context.Context, *ClearRagConversationDetailReq) (*emptypb.Empty, error)
	// 取草稿会话id，草稿态每个知识问答仅维护一条会话
	GetRagDraftConversation(context.Context, *GetRagDraftConversationReq) (*GetRagDraftConversationResp, error)
	// 取会话归属信息，供 bff 中间件校验（明细在 ES，bff 查不到，一并在这里判）
	GetRagConversationOwner(context.Context, *GetRagConversationOwnerReq) (*GetRagConversationOwnerResp, error)
	// 问答明细点赞/点踩
	RagMessageFeedback(context.Context, *RagMessageFeedbackReq) (*RagMessageFeedbackResp, error)
	// --- 会话日志 ---
	GetConversationLog(context.Context, *ConversationLogReq) (*common.ConversationLog, error)
	mustEmbedUnimplementedRagServiceServer()
}

// UnimplementedRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServiceServer struct{}

func (UnimplementedRagServiceServer) ChatRag(*ChatRagReq, grpc.ServerStreamingServer[ChatRagResp]) error {
	return status.Errorf(codes.Unimplemented, "method ChatRag not implemented")
}
func (UnimplementedRagServiceServer) CreateRag(context.Context, *CreateRagReq) (*CreateRagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRag not implemented")
}
func (UnimplementedRagServiceServer) UpdateRag(context.Context, *UpdateRagReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRag not implemented")
}
func (UnimplementedRagServiceServer) UpdateRagConfig(context.Context, *UpdateRagConfigReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRagConfig not implemented")
}
func (UnimplementedRagServiceServer) DeleteRag(context.Context, *RagDeleteReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRag not implemented")
}
func (UnimplementedRagServiceServer) GetRagDetail(context.Context, *RagDetailReq) (*RagInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRagDetail not implemented")
}
func (UnimplementedRagServiceServer) ListRag(context.Context, *RagListReq) (*RagListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRag not implemented")
}
func (UnimplementedRagServiceServer) AdminRagPageList(context.Context, *AdminRagPageListReq) (*AdminRagPageListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminRagPageList not implemented")
}
func (UnimplementedRagServiceServer) GetRagByIds(context.Context, *GetRagByIdsReq) (*AppBriefList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRagByIds not implemented")
}
func (UnimplementedRagServiceServer) CopyRag(context.Context, *CopyRagReq) (*CreateRagResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyRag not implemented")
}
func (UnimplementedRagServiceServer) PublishRag(context.Context, *PublishRagReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishRag not implemented")
}
func (UnimplementedRagServiceServer) UpdatePublishRag(context.Context, *UpdatePublishRagReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePublishRag not implemented")
}
func (UnimplementedRagServiceServer) ListPublishRagHistory(context.Context, *ListPublishRagHistoryReq) (*ListPublishRagHistoryResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublishRagHistory not implemented")
}
func (UnimplementedRagServiceServer) OverwriteRagDraft(context.Context, *OverwriteRagDraftReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OverwriteRagDraft not implemented")
}
func (UnimplementedRagServiceServer) GetPublishRagDesc(context.Context, *GetPublishRagDescReq) (*GetPublishRagDescResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishRagDesc not implemented")
}
func (UnimplementedRagServiceServer) GetPublishRagDescBatch(context.Context, *GetPublishRagDescBatchReq) (*GetPublishRagDescBatchResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublishRagDescBatch not implemented")
}
func (UnimplementedRagServiceServer) CreateRagConversation(context.Context, *CreateRagConversationReq) (*CreateRagConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRagConversation not implemented")
}
func (UnimplementedRagServiceServer) DeleteRagConversation(context.Context, *DeleteRagConversationReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRagConversation not implemented")
}
func (UnimplementedRagServiceServer) ListRagConversation(context.Context, *ListRagConversationReq) (*ListRagConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRagConversation not implemented")
}
func (UnimplementedRagServiceServer) ListRagConversationDetail(context.Context, *ListRagConversationDetailReq) (*ListRagConversationDetailResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRagConversationDetail not implemented")
}
func (UnimplementedRagServiceServer) ClearRagConversationDetail(context.Context, *ClearRagConversationDetailReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearRagConversationDetail not implemented")
}
func (UnimplementedRagServiceServer) GetRagDraftConversation(context.Context, *GetRagDraftConversationReq) (*GetRagDraftConversationResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRagDraftConversation not implemented")
}
func (UnimplementedRagServiceServer) GetRagConversationOwner(context.Context, *GetRagConversationOwnerReq) (*GetRagConversationOwnerResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRagConversationOwner not implemented")
}
func (UnimplementedRagServiceServer) RagMessageFeedback(context.Context, *RagMessageFeedbackReq) (*RagMessageFeedbackResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RagMessageFeedback not implemented")
}
func (UnimplementedRagServiceServer) GetConversationLog(context.Context, *ConversationLogReq) (*common.ConversationLog, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationLog not implemented")
}
func (UnimplementedRagServiceServer) mustEmbedUnimplementedRagServiceServer() {}
func (UnimplementedRagServiceServer) testEmbeddedByValue()                    {}

// UnsafeRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServiceServer will
// result in compilation errors.
type UnsafeRagServiceServer interface {
	mustEmbedUnimplementedRagServiceServer()
}

func RegisterRagServiceServer(s grpc.ServiceRegistrar, srv RagServiceServer) {
	// If the following call pancis, it indicates UnimplementedRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RagService_ServiceDesc, srv)
}

func _RagService_ChatRag_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRagReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RagServiceServer).ChatRag(m, &grpc.GenericServerStream[ChatRagReq, ChatRagResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RagService_ChatRagServer = grpc.ServerStreamingServer[ChatRagResp]

func _RagService_CreateRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).CreateRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_CreateRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).CreateRag(ctx, req.(*CreateRagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_UpdateRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).UpdateRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_UpdateRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).UpdateRag(ctx, req.(*UpdateRagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_UpdateRagConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRagConfigReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).UpdateRagConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_UpdateRagConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).UpdateRagConfig(ctx, req.(*UpdateRagConfigReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagDeleteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteRag(ctx, req.(*RagDeleteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetRagDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetRagDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetRagDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetRagDetail(ctx, req.(*RagDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ListRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ListRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ListRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ListRag(ctx, req.(*RagListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_AdminRagPageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminRagPageListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).AdminRagPageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_AdminRagPageList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).AdminRagPageList(ctx, req.(*AdminRagPageListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetRagByIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRagByIdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetRagByIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetRagByIds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetRagByIds(ctx, req.(*GetRagByIdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_CopyRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyRagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).CopyRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_CopyRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).CopyRag(ctx, req.(*CopyRagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_PublishRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).PublishRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_PublishRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).PublishRag(ctx, req.(*PublishRagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_UpdatePublishRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePublishRagReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).UpdatePublishRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_UpdatePublishRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).UpdatePublishRag(ctx, req.(*UpdatePublishRagReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ListPublishRagHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishRagHistoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ListPublishRagHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ListPublishRagHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ListPublishRagHistory(ctx, req.(*ListPublishRagHistoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_OverwriteRagDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OverwriteRagDraftReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).OverwriteRagDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_OverwriteRagDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).OverwriteRagDraft(ctx, req.(*OverwriteRagDraftReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetPublishRagDesc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishRagDescReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetPublishRagDesc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetPublishRagDesc_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetPublishRagDesc(ctx, req.(*GetPublishRagDescReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetPublishRagDescBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishRagDescBatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetPublishRagDescBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetPublishRagDescBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetPublishRagDescBatch(ctx, req.(*GetPublishRagDescBatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_CreateRagConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRagConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).CreateRagConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_CreateRagConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).CreateRagConversation(ctx, req.(*CreateRagConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_DeleteRagConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRagConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).DeleteRagConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_DeleteRagConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).DeleteRagConversation(ctx, req.(*DeleteRagConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ListRagConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRagConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ListRagConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ListRagConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ListRagConversation(ctx, req.(*ListRagConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ListRagConversationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRagConversationDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ListRagConversationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ListRagConversationDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ListRagConversationDetail(ctx, req.(*ListRagConversationDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_ClearRagConversationDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearRagConversationDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).ClearRagConversationDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_ClearRagConversationDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).ClearRagConversationDetail(ctx, req.(*ClearRagConversationDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetRagDraftConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRagDraftConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetRagDraftConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetRagDraftConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetRagDraftConversation(ctx, req.(*GetRagDraftConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetRagConversationOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRagConversationOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetRagConversationOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetRagConversationOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetRagConversationOwner(ctx, req.(*GetRagConversationOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_RagMessageFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RagMessageFeedbackReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).RagMessageFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_RagMessageFeedback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).RagMessageFeedback(ctx, req.(*RagMessageFeedbackReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RagService_GetConversationLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConversationLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServiceServer).GetConversationLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RagService_GetConversationLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServiceServer).GetConversationLog(ctx, req.(*ConversationLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RagService_ServiceDesc is the grpc.ServiceDesc for RagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag_service.RagService",
	HandlerType: (*RagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRag",
			Handler:    _RagService_CreateRag_Handler,
		},
		{
			MethodName: "UpdateRag",
			Handler:    _RagService_UpdateRag_Handler,
		},
		{
			MethodName: "UpdateRagConfig",
			Handler:    _RagService_UpdateRagConfig_Handler,
		},
		{
			MethodName: "DeleteRag",
			Handler:    _RagService_DeleteRag_Handler,
		},
		{
			MethodName: "GetRagDetail",
			Handler:    _RagService_GetRagDetail_Handler,
		},
		{
			MethodName: "ListRag",
			Handler:    _RagService_ListRag_Handler,
		},
		{
			MethodName: "AdminRagPageList",
			Handler:    _RagService_AdminRagPageList_Handler,
		},
		{
			MethodName: "GetRagByIds",
			Handler:    _RagService_GetRagByIds_Handler,
		},
		{
			MethodName: "CopyRag",
			Handler:    _RagService_CopyRag_Handler,
		},
		{
			MethodName: "PublishRag",
			Handler:    _RagService_PublishRag_Handler,
		},
		{
			MethodName: "UpdatePublishRag",
			Handler:    _RagService_UpdatePublishRag_Handler,
		},
		{
			MethodName: "ListPublishRagHistory",
			Handler:    _RagService_ListPublishRagHistory_Handler,
		},
		{
			MethodName: "OverwriteRagDraft",
			Handler:    _RagService_OverwriteRagDraft_Handler,
		},
		{
			MethodName: "GetPublishRagDesc",
			Handler:    _RagService_GetPublishRagDesc_Handler,
		},
		{
			MethodName: "GetPublishRagDescBatch",
			Handler:    _RagService_GetPublishRagDescBatch_Handler,
		},
		{
			MethodName: "CreateRagConversation",
			Handler:    _RagService_CreateRagConversation_Handler,
		},
		{
			MethodName: "DeleteRagConversation",
			Handler:    _RagService_DeleteRagConversation_Handler,
		},
		{
			MethodName: "ListRagConversation",
			Handler:    _RagService_ListRagConversation_Handler,
		},
		{
			MethodName: "ListRagConversationDetail",
			Handler:    _RagService_ListRagConversationDetail_Handler,
		},
		{
			MethodName: "ClearRagConversationDetail",
			Handler:    _RagService_ClearRagConversationDetail_Handler,
		},
		{
			MethodName: "GetRagDraftConversation",
			Handler:    _RagService_GetRagDraftConversation_Handler,
		},
		{
			MethodName: "GetRagConversationOwner",
			Handler:    _RagService_GetRagConversationOwner_Handler,
		},
		{
			MethodName: "RagMessageFeedback",
			Handler:    _RagService_RagMessageFeedback_Handler,
		},
		{
			MethodName: "GetConversationLog",
			Handler:    _RagService_GetConversationLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatRag",
			Handler:       _RagService_ChatRag_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rag-service/rag-service.proto",
}
