// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/operate-service/notice-service.proto

package operate_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NoticeService_CreateAppNotice_FullMethodName       = "/operate_service.NoticeService/CreateAppNotice"
	NoticeService_CreateModelNotice_FullMethodName     = "/operate_service.NoticeService/CreateModelNotice"
	NoticeService_CreateKnowledgeNotice_FullMethodName = "/operate_service.NoticeService/CreateKnowledgeNotice"
	NoticeService_GetUnreadCount_FullMethodName        = "/operate_service.NoticeService/GetUnreadCount"
	NoticeService_ListNotice_FullMethodName            = "/operate_service.NoticeService/ListNotice"
	NoticeService_ReadNotice_FullMethodName            = "/operate_service.NoticeService/ReadNotice"
	NoticeService_ReadAllNotice_FullMethodName         = "/operate_service.NoticeService/ReadAllNotice"
	NoticeService_DeleteNotice_FullMethodName          = "/operate_service.NoticeService/DeleteNotice"
)

// NoticeServiceClient is the client API for NoticeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 消息中心（消息域独立 service，与 OperateService 并列双注册）
type NoticeServiceClient interface {
	// 应用：发布版本/删除（发布版本 → 范围收「已上线」；删除 → 范围收「已下线」；
	CreateAppNotice(ctx context.Context, in *CreateAppNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error)
	// 模型：导入/删除/停用启用（导入/启用 → 范围收「上线」；删除/停用 → 范围收「下线」）
	CreateModelNotice(ctx context.Context, in *CreateModelNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error)
	// 知识库：共享/取消共享/改权限/删除（名单增减维度）
	CreateKnowledgeNotice(ctx context.Context, in *CreateKnowledgeNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error)
	// 未读总数 + 分类角标
	GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error)
	// 已读+未读混排，每条带 isRead（isRead = s.IsRead OR (CreatedAt,ID)≤水位）
	ListNotice(ctx context.Context, in *ListNoticeReq, opts ...grpc.CallOption) (*ListNoticeResp, error)
	// 单条已读：upsert user_status IsRead=TRUE（按 messageId+uid+oid）
	ReadNotice(ctx context.Context, in *ReadNoticeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 一键已读：快照边界 + read_watermark 单行成对字典序单调更新（全部未读，不分类别）
	ReadAllNotice(ctx context.Context, in *ReadAllNoticeReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 软删：upsert user_status IsDeleted=TRUE（无行则 INSERT）
	DeleteNotice(ctx context.Context, in *DeleteNoticeReq, opts ...grpc.CallOption) (*DeleteNoticeResp, error)
}

type noticeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoticeServiceClient(cc grpc.ClientConnInterface) NoticeServiceClient {
	return &noticeServiceClient{cc}
}

func (c *noticeServiceClient) CreateAppNotice(ctx context.Context, in *CreateAppNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNoticeResp)
	err := c.cc.Invoke(ctx, NoticeService_CreateAppNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) CreateModelNotice(ctx context.Context, in *CreateModelNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNoticeResp)
	err := c.cc.Invoke(ctx, NoticeService_CreateModelNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) CreateKnowledgeNotice(ctx context.Context, in *CreateKnowledgeNoticeReq, opts ...grpc.CallOption) (*CreateNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNoticeResp)
	err := c.cc.Invoke(ctx, NoticeService_CreateKnowledgeNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) GetUnreadCount(ctx context.Context, in *GetUnreadCountReq, opts ...grpc.CallOption) (*GetUnreadCountResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUnreadCountResp)
	err := c.cc.Invoke(ctx, NoticeService_GetUnreadCount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) ListNotice(ctx context.Context, in *ListNoticeReq, opts ...grpc.CallOption) (*ListNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNoticeResp)
	err := c.cc.Invoke(ctx, NoticeService_ListNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) ReadNotice(ctx context.Context, in *ReadNoticeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NoticeService_ReadNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) ReadAllNotice(ctx context.Context, in *ReadAllNoticeReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, NoticeService_ReadAllNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noticeServiceClient) DeleteNotice(ctx context.Context, in *DeleteNoticeReq, opts ...grpc.CallOption) (*DeleteNoticeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNoticeResp)
	err := c.cc.Invoke(ctx, NoticeService_DeleteNotice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoticeServiceServer is the server API for NoticeService service.
// All implementations must embed UnimplementedNoticeServiceServer
// for forward compatibility.
//
// 消息中心（消息域独立 service，与 OperateService 并列双注册）
type NoticeServiceServer interface {
	// 应用：发布版本/删除（发布版本 → 范围收「已上线」；删除 → 范围收「已下线」；
	CreateAppNotice(context.Context, *CreateAppNoticeReq) (*CreateNoticeResp, error)
	// 模型：导入/删除/停用启用（导入/启用 → 范围收「上线」；删除/停用 → 范围收「下线」）
	CreateModelNotice(context.Context, *CreateModelNoticeReq) (*CreateNoticeResp, error)
	// 知识库：共享/取消共享/改权限/删除（名单增减维度）
	CreateKnowledgeNotice(context.Context, *CreateKnowledgeNoticeReq) (*CreateNoticeResp, error)
	// 未读总数 + 分类角标
	GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error)
	// 已读+未读混排，每条带 isRead（isRead = s.IsRead OR (CreatedAt,ID)≤水位）
	ListNotice(context.Context, *ListNoticeReq) (*ListNoticeResp, error)
	// 单条已读：upsert user_status IsRead=TRUE（按 messageId+uid+oid）
	ReadNotice(context.Context, *ReadNoticeReq) (*emptypb.Empty, error)
	// 一键已读：快照边界 + read_watermark 单行成对字典序单调更新（全部未读，不分类别）
	ReadAllNotice(context.Context, *ReadAllNoticeReq) (*emptypb.Empty, error)
	// 软删：upsert user_status IsDeleted=TRUE（无行则 INSERT）
	DeleteNotice(context.Context, *DeleteNoticeReq) (*DeleteNoticeResp, error)
	mustEmbedUnimplementedNoticeServiceServer()
}

// UnimplementedNoticeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNoticeServiceServer struct{}

func (UnimplementedNoticeServiceServer) CreateAppNotice(context.Context, *CreateAppNoticeReq) (*CreateNoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAppNotice not implemented")
}
func (UnimplementedNoticeServiceServer) CreateModelNotice(context.Context, *CreateModelNoticeReq) (*CreateNoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateModelNotice not implemented")
}
func (UnimplementedNoticeServiceServer) CreateKnowledgeNotice(context.Context, *CreateKnowledgeNoticeReq) (*CreateNoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateKnowledgeNotice not implemented")
}
func (UnimplementedNoticeServiceServer) GetUnreadCount(context.Context, *GetUnreadCountReq) (*GetUnreadCountResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUnreadCount not implemented")
}
func (UnimplementedNoticeServiceServer) ListNotice(context.Context, *ListNoticeReq) (*ListNoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNotice not implemented")
}
func (UnimplementedNoticeServiceServer) ReadNotice(context.Context, *ReadNoticeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadNotice not implemented")
}
func (UnimplementedNoticeServiceServer) ReadAllNotice(context.Context, *ReadAllNoticeReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAllNotice not implemented")
}
func (UnimplementedNoticeServiceServer) DeleteNotice(context.Context, *DeleteNoticeReq) (*DeleteNoticeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNotice not implemented")
}
func (UnimplementedNoticeServiceServer) mustEmbedUnimplementedNoticeServiceServer() {}
func (UnimplementedNoticeServiceServer) testEmbeddedByValue()                       {}

// UnsafeNoticeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoticeServiceServer will
// result in compilation errors.
type UnsafeNoticeServiceServer interface {
	mustEmbedUnimplementedNoticeServiceServer()
}

func RegisterNoticeServiceServer(s grpc.ServiceRegistrar, srv NoticeServiceServer) {
	// If the following call pancis, it indicates UnimplementedNoticeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NoticeService_ServiceDesc, srv)
}

func _NoticeService_CreateAppNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAppNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).CreateAppNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_CreateAppNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).CreateAppNotice(ctx, req.(*CreateAppNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_CreateModelNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).CreateModelNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_CreateModelNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).CreateModelNotice(ctx, req.(*CreateModelNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_CreateKnowledgeNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKnowledgeNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).CreateKnowledgeNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_CreateKnowledgeNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).CreateKnowledgeNotice(ctx, req.(*CreateKnowledgeNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_GetUnreadCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUnreadCountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).GetUnreadCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_GetUnreadCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).GetUnreadCount(ctx, req.(*GetUnreadCountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_ListNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).ListNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_ListNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).ListNotice(ctx, req.(*ListNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_ReadNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).ReadNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_ReadNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).ReadNotice(ctx, req.(*ReadNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_ReadAllNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).ReadAllNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_ReadAllNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).ReadAllNotice(ctx, req.(*ReadAllNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoticeService_DeleteNotice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNoticeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoticeServiceServer).DeleteNotice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoticeService_DeleteNotice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoticeServiceServer).DeleteNotice(ctx, req.(*DeleteNoticeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NoticeService_ServiceDesc is the grpc.ServiceDesc for NoticeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoticeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "operate_service.NoticeService",
	HandlerType: (*NoticeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAppNotice",
			Handler:    _NoticeService_CreateAppNotice_Handler,
		},
		{
			MethodName: "CreateModelNotice",
			Handler:    _NoticeService_CreateModelNotice_Handler,
		},
		{
			MethodName: "CreateKnowledgeNotice",
			Handler:    _NoticeService_CreateKnowledgeNotice_Handler,
		},
		{
			MethodName: "GetUnreadCount",
			Handler:    _NoticeService_GetUnreadCount_Handler,
		},
		{
			MethodName: "ListNotice",
			Handler:    _NoticeService_ListNotice_Handler,
		},
		{
			MethodName: "ReadNotice",
			Handler:    _NoticeService_ReadNotice_Handler,
		},
		{
			MethodName: "ReadAllNotice",
			Handler:    _NoticeService_ReadAllNotice_Handler,
		},
		{
			MethodName: "DeleteNotice",
			Handler:    _NoticeService_DeleteNotice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/operate-service/notice-service.proto",
}
