// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.4
// source: proto/knowledgebase-template-service/knowledgebase-template-service.proto

package knowledgebase_template_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeBaseTemplateService_GetParseTemplateList_FullMethodName = "/knowledgebase_template_service.KnowledgeBaseTemplateService/GetParseTemplateList"
	KnowledgeBaseTemplateService_CreateParseTemplate_FullMethodName  = "/knowledgebase_template_service.KnowledgeBaseTemplateService/CreateParseTemplate"
	KnowledgeBaseTemplateService_UpdateParseTemplate_FullMethodName  = "/knowledgebase_template_service.KnowledgeBaseTemplateService/UpdateParseTemplate"
	KnowledgeBaseTemplateService_DeleteParseTemplate_FullMethodName  = "/knowledgebase_template_service.KnowledgeBaseTemplateService/DeleteParseTemplate"
)

// KnowledgeBaseTemplateServiceClient is the client API for KnowledgeBaseTemplateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeBaseTemplateServiceClient interface {
	// 查询解析模板列表
	GetParseTemplateList(ctx context.Context, in *GetParseTemplateListReq, opts ...grpc.CallOption) (*GetParseTemplateListResp, error)
	// 新增解析模板
	CreateParseTemplate(ctx context.Context, in *CreateParseTemplateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 编辑解析模板
	UpdateParseTemplate(ctx context.Context, in *UpdateParseTemplateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// 删除解析模板
	DeleteParseTemplate(ctx context.Context, in *DeleteParseTemplateReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type knowledgeBaseTemplateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeBaseTemplateServiceClient(cc grpc.ClientConnInterface) KnowledgeBaseTemplateServiceClient {
	return &knowledgeBaseTemplateServiceClient{cc}
}

func (c *knowledgeBaseTemplateServiceClient) GetParseTemplateList(ctx context.Context, in *GetParseTemplateListReq, opts ...grpc.CallOption) (*GetParseTemplateListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetParseTemplateListResp)
	err := c.cc.Invoke(ctx, KnowledgeBaseTemplateService_GetParseTemplateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseTemplateServiceClient) CreateParseTemplate(ctx context.Context, in *CreateParseTemplateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseTemplateService_CreateParseTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseTemplateServiceClient) UpdateParseTemplate(ctx context.Context, in *UpdateParseTemplateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseTemplateService_UpdateParseTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeBaseTemplateServiceClient) DeleteParseTemplate(ctx context.Context, in *DeleteParseTemplateReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, KnowledgeBaseTemplateService_DeleteParseTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeBaseTemplateServiceServer is the server API for KnowledgeBaseTemplateService service.
// All implementations must embed UnimplementedKnowledgeBaseTemplateServiceServer
// for forward compatibility.
type KnowledgeBaseTemplateServiceServer interface {
	// 查询解析模板列表
	GetParseTemplateList(context.Context, *GetParseTemplateListReq) (*GetParseTemplateListResp, error)
	// 新增解析模板
	CreateParseTemplate(context.Context, *CreateParseTemplateReq) (*emptypb.Empty, error)
	// 编辑解析模板
	UpdateParseTemplate(context.Context, *UpdateParseTemplateReq) (*emptypb.Empty, error)
	// 删除解析模板
	DeleteParseTemplate(context.Context, *DeleteParseTemplateReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedKnowledgeBaseTemplateServiceServer()
}

// UnimplementedKnowledgeBaseTemplateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeBaseTemplateServiceServer struct{}

func (UnimplementedKnowledgeBaseTemplateServiceServer) GetParseTemplateList(context.Context, *GetParseTemplateListReq) (*GetParseTemplateListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParseTemplateList not implemented")
}
func (UnimplementedKnowledgeBaseTemplateServiceServer) CreateParseTemplate(context.Context, *CreateParseTemplateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateParseTemplate not implemented")
}
func (UnimplementedKnowledgeBaseTemplateServiceServer) UpdateParseTemplate(context.Context, *UpdateParseTemplateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParseTemplate not implemented")
}
func (UnimplementedKnowledgeBaseTemplateServiceServer) DeleteParseTemplate(context.Context, *DeleteParseTemplateReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteParseTemplate not implemented")
}
func (UnimplementedKnowledgeBaseTemplateServiceServer) mustEmbedUnimplementedKnowledgeBaseTemplateServiceServer() {
}
func (UnimplementedKnowledgeBaseTemplateServiceServer) testEmbeddedByValue() {}

// UnsafeKnowledgeBaseTemplateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeBaseTemplateServiceServer will
// result in compilation errors.
type UnsafeKnowledgeBaseTemplateServiceServer interface {
	mustEmbedUnimplementedKnowledgeBaseTemplateServiceServer()
}

func RegisterKnowledgeBaseTemplateServiceServer(s grpc.ServiceRegistrar, srv KnowledgeBaseTemplateServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeBaseTemplateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeBaseTemplateService_ServiceDesc, srv)
}

func _KnowledgeBaseTemplateService_GetParseTemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParseTemplateListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseTemplateServiceServer).GetParseTemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseTemplateService_GetParseTemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseTemplateServiceServer).GetParseTemplateList(ctx, req.(*GetParseTemplateListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseTemplateService_CreateParseTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParseTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseTemplateServiceServer).CreateParseTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseTemplateService_CreateParseTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseTemplateServiceServer).CreateParseTemplate(ctx, req.(*CreateParseTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseTemplateService_UpdateParseTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParseTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseTemplateServiceServer).UpdateParseTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseTemplateService_UpdateParseTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseTemplateServiceServer).UpdateParseTemplate(ctx, req.(*UpdateParseTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeBaseTemplateService_DeleteParseTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParseTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeBaseTemplateServiceServer).DeleteParseTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeBaseTemplateService_DeleteParseTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeBaseTemplateServiceServer).DeleteParseTemplate(ctx, req.(*DeleteParseTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeBaseTemplateService_ServiceDesc is the grpc.ServiceDesc for KnowledgeBaseTemplateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeBaseTemplateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "knowledgebase_template_service.KnowledgeBaseTemplateService",
	HandlerType: (*KnowledgeBaseTemplateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetParseTemplateList",
			Handler:    _KnowledgeBaseTemplateService_GetParseTemplateList_Handler,
		},
		{
			MethodName: "CreateParseTemplate",
			Handler:    _KnowledgeBaseTemplateService_CreateParseTemplate_Handler,
		},
		{
			MethodName: "UpdateParseTemplate",
			Handler:    _KnowledgeBaseTemplateService_UpdateParseTemplate_Handler,
		},
		{
			MethodName: "DeleteParseTemplate",
			Handler:    _KnowledgeBaseTemplateService_DeleteParseTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/knowledgebase-template-service/knowledgebase-template-service.proto",
}
