#!/usr/bin/env python3
"""
Comprehensive Chinese to English translation script.
Translates all Chinese characters to English equivalents.
"""

import os
import re

# Comprehensive translation dictionary
TRANSLATIONS = {
    # Common words and phrases
    '判断': 'Check',
    '文件': 'file',
    '是否': 'whether',
    '为': 'is',
    '图片': 'image',
    '类型': 'type',
    '安全': 'security',
    '限制': 'limit',
    '数量': 'count',
    '大小': 'size',
    '白名单': 'whitelist',
    '单个': 'single',
    '默认': 'default',
    '第一个': 'first',
    '有效': 'valid',
    '如果': 'if',
    '没有': 'no',
    '直接': 'directly',
    '返回': 'return',
    '非': 'non',
    '个': '',
    '覆盖': 'override',
    '之前': 'previous',
    '过滤': 'filter',
    '非法': 'illegal',
    '检查': 'check',
    '对象': 'object',
    '必须': 'must',
    '有': 'have',
    '属性': 'property',
    '存在': 'exist',
    '并且': 'and',
    '数字': 'number',
    '当前': 'current',
    '确保': 'ensure',
    '一致': 'consistent',
    '但': 'but',
    '拒绝': 'reject',
    '保持': 'keep',
    '只能': 'can only',
    '上传': 'upload',
    '使用': 'use',
    '提示': 'tip',
    '被': 'rejected',
    '释放': 'release',
    '旧': 'old',
    '避免': 'avoid',
    '内存': 'memory',
    '泄漏': 'leak',
    '格式化': 'format',
    '日期': 'date',
    '格式': 'format',
    '字符串': 'string',
    '后': 'after',
    '深拷贝': 'deep copy',
    '要': 'to',
    '拷贝': 'copy',
    '防抖': 'debounce',
    '函数': 'function',
    '延迟': 'delay',
    '时间': 'time',
    '毫秒': 'milliseconds',
    '节流': 'throttle',
    '获取': 'get',
    '字节数': 'bytes',
    '验证': 'validate',
    '邮箱': 'email',
    '地址': 'address',
    '手机号': 'phone',
    '滚动': 'scroll',
    '到': 'to',
    '页面': 'page',
    '顶部': 'top',
    '复制': 'copy',
    '文本': 'text',
    '剪贴板': 'clipboard',
    '结果': 'result',
    '兼容': 'compatible',
    '浏览器': 'browser',
    '处理': 'handle',
    '引用': 'citation',
    '点击': 'click',
    '事件': 'event',
    '配置': 'configuration',
    '选项': 'options',
    '会话': 'session',
    '状态': 'status',
    '数据': 'data',
    '元素': 'element',
    '选择器': 'selector',
    '容器': 'container',
    '切换': 'toggle',
    '折叠': 'collapse',
    '回调': 'callback',
    '最近': 'nearest',
    '父级': 'parent',
    '索引': 'index',
    '结构': 'structure',
    '严格': 'strictly',
    '按照': 'according to',
    '组件': 'component',
    '中': 'in',
    '逻辑': 'logic',
    '底部': 'bottom',
    '阻止': 'prevent',
    '冒泡': 'bubbling',
    '空': 'empty',
    '对话': 'conversation',
    '历史': 'history',
    '列表': 'list',
    '内容': 'content',
    '用户': 'user',
    '输入': 'input',
    '系统': 'system',
    '回复': 'response',
    '清空': 'clear',
    '删除': 'delete',
    '新建': 'new',
    '标题': 'title',
    '重命名': 'rename',
    '确认': 'confirm',
    '取消': 'cancel',
    '保存': 'save',
    '编辑': 'edit',
    '新增': 'add',
    '添加': 'add',
    '搜索': 'search',
    '查询': 'query',
    '筛选': 'filter',
    '排序': 'sort',
    '导出': 'export',
    '导入': 'import',
    '下载': 'download',
    '刷新': 'refresh',
    '关闭': 'close',
    '提交': 'submit',
    '重置': 'reset',
    '下一步': 'next',
    '上一步': 'previous',
    '完成': 'complete',
    '操作': 'operation',
    '名称': 'name',
    '描述': 'description',
    '详情': 'details',
    '创建': 'create',
    '更新': 'update',
    '修改': 'modify',
    '成功': 'success',
    '失败': 'failed',
    '错误': 'error',
    '警告': 'warning',
    '加载': 'loading',
    '暂无': 'no',
    '请': 'please',
    '选择': 'select',
    '必填': 'required',
    '选填': 'optional',
    '已': 'already',
    '未': 'not',
    '正在': 'in progress',
    '完成': 'completed',
    '进行中': 'in progress',
    '等待': 'waiting',
    '开始': 'start',
    '结束': 'end',
    '暂停': 'pause',
    '继续': 'continue',
    '停止': 'stop',
    '重新': 'restart',
    '重试': 'retry',
    '发送': 'send',
    '接收': 'receive',
    '消息': 'message',
    '通知': 'notification',
    '提醒': 'reminder',
    '设置': 'settings',
    '配置': 'configuration',
    '参数': 'parameter',
    '值': 'value',
    '键': 'key',
    '项': 'item',
    '条': 'item',
    '行': 'row',
    '列': 'column',
    '表': 'table',
    '表格': 'table',
    '表单': 'form',
    '字段': 'field',
    '标签': 'tag',
    '分类': 'category',
    '分组': 'group',
    '排序': 'sort',
    '筛选': 'filter',
    '搜索': 'search',
    '查找': 'find',
    '替换': 'replace',
    '匹配': 'match',
    '包含': 'contain',
    '不包含': 'not contain',
    '等于': 'equal',
    '不等于': 'not equal',
    '大于': 'greater than',
    '小于': 'less than',
    '范围': 'range',
    '之间': 'between',
    '或': 'or',
    '且': 'and',
    '非': 'not',
    '全部': 'all',
    '部分': 'partial',
    '任意': 'any',
    '每': 'each',
    '所有': 'all',
    '多个': 'multiple',
    '单个': 'single',
    '唯一': 'unique',
    '重复': 'duplicate',
    '相同': 'same',
    '不同': 'different',
    '相似': 'similar',
    '相关': 'related',
    '关联': 'associated',
    '绑定': 'bind',
    '解绑': 'unbind',
    '连接': 'connect',
    '断开': 'disconnect',
    '链接': 'link',
    '跳转': 'jump',
    '打开': 'open',
    '展开': 'expand',
    '收起': 'collapse',
    '显示': 'show',
    '隐藏': 'hide',
    '可见': 'visible',
    '不可见': 'invisible',
    '启用': 'enable',
    '禁用': 'disable',
    '激活': 'activate',
    '停用': 'deactivate',
    '锁定': 'lock',
    '解锁': 'unlock',
    '冻结': 'freeze',
    '解冻': 'unfreeze',
    '标记': 'mark',
    '取消标记': 'unmark',
    '选中': 'selected',
    '未选中': 'unselected',
    '全选': 'select all',
    '反选': 'invert selection',
    '清除': 'clear',
    '重置': 'reset',
    '恢复': 'restore',
    '撤销': 'undo',
    '重做': 'redo',
    '应用': 'apply',
    '取消': 'cancel',
    '确定': 'confirm',
    '同意': 'agree',
    '拒绝': 'reject',
    '接受': 'accept',
    '忽略': 'ignore',
    '跳过': 'skip',
    '下载': 'download',
    '上传': 'upload',
    '导入': 'import',
    '导出': 'export',
    '打印': 'print',
    '预览': 'preview',
    '查看': 'view',
    '编辑': 'edit',
    '修改': 'modify',
    '删除': 'delete',
    '移除': 'remove',
    '添加': 'add',
    '插入': 'insert',
    '追加': 'append',
    '前置': 'prepend',
    '移动': 'move',
    '复制': 'copy',
    '粘贴': 'paste',
    '剪切': 'cut',
    '分享': 'share',
    '转发': 'forward',
    '回复': 'reply',
    '评论': 'comment',
    '点赞': 'like',
    '收藏': 'favorite',
    '关注': 'follow',
    '取消关注': 'unfollow',
    '订阅': 'subscribe',
    '取消订阅': 'unsubscribe',
}

def translate_chinese_to_english(text):
    """Translate Chinese text to English"""
    result = text
    
    # Sort by length (longest first) to handle multi-character words first
    for chinese, english in sorted(TRANSLATIONS.items(), key=lambda x: len(x[0]), reverse=True):
        result = result.replace(chinese, english)
    
    return result

def process_file(file_path):
    """Process a single file"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        if not re.search(r'[\u4e00-\u9fff]', content):
            return False
        
        translated = translate_chinese_to_english(content)
        
        if translated != content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(translated)
            return True
        return False
    except Exception as e:
        print(f"Error: {file_path}: {e}")
        return False

def main():
    count = 0
    for root, dirs, files in os.walk('web/src'):
        if 'lang' in dirs:
            dirs.remove('lang')
        if 'node_modules' in dirs:
            dirs.remove('node_modules')
        
        for file in files:
            if file.endswith(('.vue', '.js')):
                fp = os.path.join(root, file)
                if process_file(fp):
                    count += 1
                    print(f"✓ {fp}")
    
    print(f"\nTranslated {count} files")

if __name__ == '__main__':
    main()

