import os
import re

# Extended glossary for frontend
glossary = {
    '复制成功': 'Copy successful',
    '复制失败': 'Copy failed',
    '复制': 'Copy',
    '连接失败，请稍后重试': 'Connection failed, please try again later',
    '上个问题没有回答完！': 'The previous question has not been answered yet!',
    '未知错误': 'Unknown error',
    '思考中': 'Thinking',
    '服务连接异常请重试！': 'Service connection exception, please try again!',
    '已建立SSE连接~': 'SSE connection established~',
    '使用工具中...': 'Using tool...',
    '的beforeLoad阶段': ' beforeLoad phase',
    '的beforeMount阶段': ' beforeMount phase',
    '的afterMount阶段': ' afterMount phase',
    '的beforeUnmount阶段': ' beforeUnmount phase',
    '的afterUnmount阶段': ' afterUnmount phase',
    '通用 mixins 方法': 'Common mixins methods',
    '提供项目中常用的工具方法和生命周期钩子': 'Provide common utility methods and lifecycle hooks used in the project',
    '通用拖拽封装': 'Common drag and drop encapsulation',
    '监听拖拽的容器选择器': 'Container selector for listening to drag and drop',
    '文件落下后的处理回调': 'Callback for handling files after they are dropped',
    '图片类型文件的最大上传数量': 'Maximum number of image files to upload',
    '默认最大上传数量（已废弃，优先使用 maxImageFiles）': 'Default maximum upload quantity (deprecated, use maxImageFiles first)',
    '格式化日期': 'Format date',
    '请选择': 'Please select',
    '请输入': 'Please enter',
    '加载中': 'Loading',
    '暂无数据': 'No data',
    '成功': 'Success',
    '失败': 'Failed',
    '错误': 'Error',
    '警告': 'Warning',
    '提示': 'Tip',
    '确认': 'Confirm',
    '取消': 'Cancel',
    '保存': 'Save',
    '删除': 'Delete',
    '编辑': 'Edit',
    '查询': 'Query',
    '重置': 'Reset',
    '搜索': 'Search',
    '详情': 'Details',
    '状态': 'Status',
    '操作': 'Operation',
    '创建时间': 'Create Time',
    '更新时间': 'Update Time',
    '名称': 'Name',
    '描述': 'Description',
    '类型': 'Type',
    '备注': 'Remark',
    '序号': 'No.',
    '全选': 'Select All',
    '批量删除': 'Batch Delete',
    '导出': 'Export',
    '导入': 'Import',
    '下载': 'Download',
    '上传': 'Upload',
    '启用': 'Enable',
    '禁用': 'Disable',
    '是': 'Yes',
    '否': 'No',
    '男': 'Male',
    '女': 'Female',
    '请填写': 'Please fill in',
    '不能为空': 'Cannot be empty',
    '已存在': 'Already exists',
    '不存在': 'Does not exist',
    '请选择日期': 'Please select date',
    '请选择时间': 'Please select time',
    '开始日期': 'Start Date',
    '结束日期': 'End Date',
    '至': 'to',
    '请输入关键字': 'Please enter keywords',
    '请输入查询内容': 'Please enter query content',
    '请输入正确的手机号': 'Please enter a valid mobile number',
    '请输入正确的邮箱': 'Please enter a valid email',
    '请输入正确的身份证号': 'Please enter a valid ID card number',
    '系统异常': 'System Exception',
    '网络异常': 'Network Exception',
    '请求超时': 'Request Timeout',
    '服务器内部错误': 'Internal Server Error',
    '未授权': 'Unauthorized',
    '禁止访问': 'Forbidden',
    '资源未找到': 'Resource Not Found',
    '方法不允许': 'Method Not Allowed',
    '请求实体过大': 'Request Entity Too Large',
    '不支持的媒体类型': 'Unsupported Media Type',
    '请求过多': 'Too Many Requests',
    '服务不可用': 'Service Unavailable',
    '网关超时': 'Gateway Timeout',
    'HTTP版本不支持': 'HTTP Version Not Supported',
    '连接超时': 'Connection Timeout',
    '连接被拒绝': 'Connection Refused',
    '连接重置': 'Connection Reset',
    '连接中断': 'Connection Aborted',
    '网络不可达': 'Network Unreachable',
    '主机不可达': 'Host Unreachable',
    '协议错误': 'Protocol Error',
    '解析错误': 'Parse Error',
    'IO错误': 'IO Error',
    '文件未找到': 'File Not Found',
    '权限拒绝': 'Permission Denied',
    '磁盘空间不足': 'Disk Space Insufficient',
    '内存不足': 'Out of Memory',
    '堆栈溢出': 'Stack Overflow',
    '除零错误': 'Division by Zero',
    '空指针异常': 'Null Pointer Exception',
    '数组越界': 'Array Index Out of Bounds',
    '类型转换异常': 'Class Cast Exception',
    '算术异常': 'Arithmetic Exception',
    '非法参数': 'IllegalArgument',
    '非法状态': 'IllegalState',
    '不支持的操作': 'UnsupportedOperation',
    '并发修改': 'ConcurrentModification',
    '中断异常': 'Interrupted',
    '超时异常': 'Timeout',
    '执行异常': 'Execution',
    '未知异常': 'Unknown',
    '系统错误': 'System Error',
    '业务错误': 'Business Error',
    '数据错误': 'Data Error',
    '逻辑错误': 'Logic Error',
    '配置错误': 'Configuration Error',
    '环境错误': 'Environment Error',
    '依赖错误': 'Dependency Error',
    '接口错误': 'Interface Error',
    '数据库错误': 'Database Error',
    '缓存错误': 'Cache Error',
    '消息队列错误': 'Message Queue Error',
    '文件系统错误': 'File System Error',
    '网络错误': 'Network Error',
    '安全错误': 'Security Error',
    '权限错误': 'Permission Error',
    '认证错误': 'Authentication Error',
    '授权错误': 'Authorization Error',
    '验证错误': 'Validation Error',
    '参数错误': 'Parameter Error',
    '格式错误': 'Format Error',
    '编码错误': 'Encoding Error',
    '解码错误': 'Decoding Error',
    '加密错误': 'Encryption Error',
    '解密错误': 'Decryption Error',
    '签名错误': 'Signature Error',
    '验签错误': 'Signature Verification Error',
    '压缩错误': 'Compression Error',
    '解压错误': 'Decompression Error',
    '序列化错误': 'Serialization Error',
    '反序列化错误': 'Deserialization Error',
    '上传错误': 'Upload Error',
    '下载错误': 'Download Error',
    '导入错误': 'Import Error',
    '导出错误': 'Export Error',
    '打印错误': 'Print Error',
    '预览错误': 'Preview Error',
    '发送错误': 'Send Error',
    '接收错误': 'Receive Error',
    '处理错误': 'Process Error',
    '保存错误': 'Save Error',
    '删除错误': 'Delete Error',
    '更新错误': 'Update Error',
    '查询错误': 'Query Error',
    '加载错误': 'Load Error',
    '初始化错误': 'Initialization Error',
    '启动错误': 'Start Error',
    '停止错误': 'Stop Error',
    '重启错误': 'Restart Error',
    '关闭错误': 'Close Error',
    '连接错误': 'Connection Error',
    '断开错误': 'Disconnect Error',
    '重连错误': 'Reconnect Error',
    '登录错误': 'Login Error',
    '登出错误': 'Logout Error',
    '注册错误': 'Register Error',
    '注销错误': 'Unregister Error',
    '绑定错误': 'Bind Error',
    '解绑错误': 'Unbind Error',
    '授权错误': 'Grant Error',
    '撤销错误': 'Revoke Error',
    '审核错误': 'Audit Error',
    '审批错误': 'Approve Error',
    '拒绝错误': 'Reject Error',
    '提交错误': 'Submit Error',
    '撤回错误': 'Withdraw Error',
    '发布错误': 'Publish Error',
    '下架错误': 'Unpublish Error',
    '部署错误': 'Deploy Error',
    '回滚错误': 'Rollback Error',
    '扩容错误': 'Scale Out Error',
    '缩容错误': 'Scale In Error',
    '升级错误': 'Upgrade Error',
    '降级错误': 'Downgrade Error',
    '迁移错误': 'Migrate Error',
    '备份错误': 'Backup Error',
    '恢复错误': 'Restore Error',
    '监控错误': 'Monitor Error',
    '告警错误': 'Alert Error',
    '日志错误': 'Log Error',
    '统计错误': 'Statistic Error',
    '分析错误': 'Analyze Error',
    '报表错误': 'Report Error',
    '通知错误': 'Notify Error',
    '推送错误': 'Push Error',
    '短信错误': 'SMS Error',
    '邮件错误': 'Email Error',
    '微信错误': 'WeChat Error',
    '钉钉错误': 'DingTalk Error',
    '飞书错误': 'Lark Error',
    '企业微信错误': 'WeCom Error',
    '机器人错误': 'Robot Error',
    '语音错误': 'Voice Error',
    '视频错误': 'Video Error',
    '直播错误': 'Live Error',
    '会议错误': 'Meeting Error',
    '聊天错误': 'Chat Error',
    '客服错误': 'Customer Service Error',
    '工单错误': 'Ticket Error',
    '任务错误': 'Task Error',
    '日程错误': 'Schedule Error',
    '日历错误': 'Calendar Error',
    '提醒错误': 'Reminder Error',
    '笔记错误': 'Note Error',
    '文档错误': 'Document Error',
    '知识库错误': 'Knowledge Base Error',
    'Wiki错误': 'Wiki Error',
    '博客错误': 'Blog Error',
    '论坛错误': 'Forum Error',
    '问答错误': 'Q&A Error',
    '社区错误': 'Community Error',
    '商城错误': 'Mall Error',
    '支付错误': 'Payment Error',
    '订单错误': 'Order Error',
    '商品错误': 'Product Error',
    '库存错误': 'Stock Error',
    '物流错误': 'Logistics Error',
    '售后错误': 'After-sales Error',
    '评价错误': 'Review Error',
    '积分错误': 'Points Error',
    '优惠券错误': 'Coupon Error',
    '活动错误': 'Activity Error',
    '广告错误': 'Ad Error',
    '推广错误': 'Promotion Error',
    '营销错误': 'Marketing Error',
    '会员错误': 'Member Error',
    '用户错误': 'User Error',
    '账户错误': 'Account Error',
    '角色错误': 'Role Error',
    '组织错误': 'Organization Error',
    '部门错误': 'Department Error',
    '岗位错误': 'Position Error',
    '职级错误': 'Rank Error',
    '员工错误': 'Employee Error',
    '考勤错误': 'Attendance Error',
    '绩效错误': 'Performance Error',
    '薪资错误': 'Salary Error',
    '社保错误': 'Social Security Error',
    '公积金错误': 'Provident Fund Error',
    '招聘错误': 'Recruitment Error',
    '培训错误': 'Training Error',
    '资产错误': 'Asset Error',
    '合同错误': 'Contract Error',
    '采购错误': 'Purchase Error',
    '供应商错误': 'Supplier Error',
    '客户错误': 'Customer Error',
    '项目错误': 'Project Error',
    '产品错误': 'Product Error',
    '需求错误': 'Requirement Error',
    '缺陷错误': 'Defect Error',
    '用例错误': 'Test Case Error',
    '测试错误': 'Test Error',
    '发布错误': 'Release Error',
    '运维错误': 'Ops Error',
    'DevOps错误': 'DevOps Error',
    'CI/CD错误': 'CI/CD Error',
    '容器错误': 'Container Error',
    'K8s错误': 'K8s Error',
    '云原生错误': 'Cloud Native Error',
    '微服务错误': 'Microservice Error',
    '分布式错误': 'Distributed Error',
    '高并发错误': 'High Concurrency Error',
    '高可用错误': 'High Availability Error',
    '高性能错误': 'High Performance Error',
    '大数据错误': 'Big Data Error',
    'AI错误': 'AI Error',
    '区块链错误': 'Blockchain Error',
    '物联网错误': 'IoT Error',
    '5G错误': '5G Error',
    '边缘计算错误': 'Edge Computing Error',
    '数字孪生错误': 'Digital Twin Error',
    '元宇宙错误': 'Metaverse Error',
    'Web3错误': 'Web3 Error',
    'NFT错误': 'NFT Error',
    'DAO错误': 'DAO Error',
    'DeFi错误': 'DeFi Error',
    'GameFi错误': 'GameFi Error',
    'SocialFi错误': 'SocialFi Error',
    'X-to-Earn错误': 'X-to-Earn Error',
}

def replace_chinese(text):
    # Sort keys by length descending to match longest first
    sorted_keys = sorted(glossary.keys(), key=len, reverse=True)
    
    for key in sorted_keys:
        if key in text:
            # Simple string replacement
            # We might want to be careful about replacing inside other words, but Chinese chars are usually distinct
            text = text.replace(key, glossary[key])
            
    return text

def process_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        
        # Split into lines to handle comments properly-ish
        # But simple replacement on whole content might be faster and safer if we ignore comments?
        # Actually, we want to replace in comments too if requested? 
        # The user said "UI is entirely translated", implying user-facing.
        # But code comments are also part of the plan (Phase 3).
        # Let's replace everywhere for now, it's safer for "completeness".
        
        new_content = replace_chinese(content)
        
        if new_content != original_content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            return True
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
    return False

def scan_and_fix(root_dir):
    count = 0
    for root, dirs, files in os.walk(root_dir):
        if 'lang' in dirs:
            dirs.remove('lang')
            
        for file in files:
            if file.endswith(('.js', '.vue', '.html')):
                file_path = os.path.join(root, file)
                if process_file(file_path):
                    print(f"Fixed: {file_path}")
                    count += 1
    return count

print("Starting automated translation of hardcoded strings...")
fixed_count = scan_and_fix('web/src')
print(f"Finished. Modified {fixed_count} files.")
