import os
import re

# Massive glossary for Frontend comments (same as Go/Python + frontend specifics)
glossary = {
    '参数': 'Parameter',
    '返回': 'Return',
    '成功': 'Success',
    '失败': 'Failed',
    '错误': 'Error',
    '知识库': 'Knowledge Base',
    '文档': 'Document',
    '权限': 'Permission',
    '用户': 'User',
    '组织': 'Organization',
    '模型': 'Model',
    '推理': 'Inference',
    '上下文': 'Context',
    '长度': 'Length',
    '温度': 'Temperature',
    '频率惩罚': 'Frequency Penalty',
    '存在惩罚': 'Presence Penalty',
    '最大标记': 'Max Tokens',
    '视觉支持': 'Vision Support',
    '函数调用': 'Function Calling',
    '索引': 'Index',
    '名称': 'Name',
    '描述': 'Description',
    '类型': 'Type',
    '状态': 'Status',
    '校验': 'Verification',
    '查询': 'Query',
    '获取': 'Get',
    '创建': 'Create',
    '更新': 'Update',
    '删除': 'Delete',
    '日志': 'Log',
    '记录': 'Record',
    '发送': 'Send',
    '请求': 'Request',
    '响应': 'Response',
    '结果': 'Result',
    '输出': 'Output',
    '输入': 'Input',
    '配置': 'Config',
    '初始化': 'Initialize',
    '连接': 'Connect',
    '关闭': 'Close',
    '启动': 'Start',
    '停止': 'Stop',
    '执行': 'Execute',
    '处理': 'Process',
    '解析': 'Parse',
    '转换': 'Convert',
    '生成': 'Generate',
    '上传': 'Upload',
    '下载': 'Download',
    '导入': 'Import',
    '导出': 'Export',
    '批量': 'Batch',
    '列表': 'List',
    '详情': 'Detail',
    '信息': 'Info',
    '数据': 'Data',
    '时间': 'Time',
    '日期': 'Date',
    '密码': 'Password',
    '邮箱': 'Email',
    '手机号': 'Phone',
    '验证码': 'Verification Code',
    '登录': 'Login',
    '注册': 'Register',
    '鉴权': 'Auth',
    '认证': 'Authentication',
    '授权': 'Authorization',
    '角色': 'Role',
    '菜单': 'Menu',
    '按钮': 'Button',
    '接口': 'Interface',
    '服务': 'Service',
    '系统': 'System',
    '环境': 'Environment',
    '开发': 'Dev',
    '测试': 'Test',
    '生产': 'Prod',
    '部署': 'Deploy',
    '运维': 'Ops',
    '监控': 'Monitor',
    '告警': 'Alert',
    '通知': 'Notify',
    '消息': 'Message',
    '队列': 'Queue',
    '缓存': 'Cache',
    '数据库': 'Database',
    '表': 'Table',
    '字段': 'Field',
    '主键': 'Primary Key',
    '外键': 'Foreign Key',
    '事务': 'Transaction',
    '回滚': 'Rollback',
    '提交': 'Commit',
    '锁': 'Lock',
    '并发': 'Concurrency',
    '异步': 'Async',
    '同步': 'Sync',
    '线程': 'Thread',
    '协程': 'Goroutine',
    '进程': 'Process',
    '内存': 'Memory',
    '磁盘': 'Disk',
    '网络': 'Network',
    '协议': 'Protocol',
    '端口': 'Port',
    '地址': 'Address',
    '链接': 'Link',
    '路由': 'Route',
    '中间件': 'Middleware',
    '拦截器': 'Interceptor',
    '过滤器': 'Filter',
    '处理器': 'Handler',
    '控制器': 'Controller',
    '视图': 'View',
    '模板': 'Template',
    '静态资源': 'Static Resource',
    '文件上传': 'File Upload',
    '文件下载': 'File Download',
    '图片': 'Image',
    '视频': 'Video',
    '音频': 'Audio',
    '文本': 'Text',
    '富文本': 'Rich Text',
    '如果没有': 'If not',
    '如果': 'If',
    '否则': 'Otherwise',
    '但是': 'But',
    '或者': 'Or',
    '以及': 'And',
    '因为': 'Because',
    '所以': 'So',
    '为了': 'In order to',
    '注意': 'Note',
    '警告': 'Warning',
    '提示': 'Tip',
    '说明': 'Description',
    '备注': 'Remark',
    'TODO': 'TODO',
    'FIXME': 'FIXME',
    'XXX': 'XXX',
    '暂不支持': 'Not supported yet',
    '不支持': 'Not supported',
    '已废弃': 'Deprecated',
    '使用': 'Use',
    '调用': 'Call',
    '返回': 'Return',
    '需要': 'Need',
    '必须': 'Must',
    '可选': 'Optional',
    '默认': 'Default',
    '最大': 'Max',
    '最小': 'Min',
    '长度': 'Length',
    '范围': 'Range',
    '格式': 'Format',
    '例如': 'Example',
    '比如': 'For example',
    '如': 'Such as',
    '即': 'That is',
    '等': 'Etc',
    '及': 'And',
    '与': 'With',
    '或': 'Or',
    '非': 'Non',
    '是': 'Is',
    '否': 'No',
    '有': 'Has',
    '无': 'No',
    '空': 'Empty',
    '非空': 'Non-empty',
    '真': 'True',
    '假': 'False',
    '组件': 'Component',
    '页面': 'Page',
    '样式': 'Style',
    '布局': 'Layout',
    '弹窗': 'Dialog',
    '表单': 'Form',
    '表格': 'Table',
    '树': 'Tree',
    '标签': 'Tag',
    '选项卡': 'Tab',
    '导航': 'Navigation',
    '侧边栏': 'Sidebar',
    '头部': 'Header',
    '底部': 'Footer',
    '面包屑': 'Breadcrumb',
    '下拉菜单': 'Dropdown',
    '输入框': 'Input',
    '选择器': 'Select',
    '复选框': 'Checkbox',
    '单选框': 'Radio',
    '开关': 'Switch',
    '滑块': 'Slider',
    '时间选择器': 'Time Picker',
    '日期选择器': 'Date Picker',
    '上传': 'Upload',
    '评分': 'Rate',
    '颜色选择器': 'Color Picker',
    '穿梭框': 'Transfer',
    '折叠面板': 'Collapse',
    '步骤条': 'Steps',
    '加载': 'Loading',
    '消息提示': 'Message',
    '通知': 'Notification',
    '对话框': 'Dialog',
    '气泡确认框': 'Popconfirm',
    '卡片': 'Card',
    '轮播': 'Carousel',
    '头像': 'Avatar',
    '徽标': 'Badge',
    '日历': 'Calendar',
    '空状态': 'Empty',
    '骨架屏': 'Skeleton',
    '结果': 'Result',
    '异常': 'Exception',
    '水印': 'Watermark',
    '分割线': 'Divider',
    '抽屉': 'Drawer',
    '模态框': 'Modal',
    '提示框': 'Tooltip',
    '弹出框': 'Popover',
    '气泡卡片': 'Popconfirm',
    '进度条': 'Progress',
    '加载条': 'Loading Bar',
    '滚动条': 'Scrollbar',
    '无限滚动': 'Infinite Scroll',
    '虚拟列表': 'Virtual List',
    '拖拽': 'Drag',
    '放置': 'Drop',
    '排序': 'Sort',
    '筛选': 'Filter',
    '搜索': 'Search',
    '重置': 'Reset',
    '提交': 'Submit',
    '取消': 'Cancel',
    '确认': 'Confirm',
    '保存': 'Save',
    '删除': 'Delete',
    '编辑': 'Edit',
    '查看': 'View',
    '详情': 'Detail',
    '新增': 'Add',
    '修改': 'Modify',
    '复制': 'Copy',
    '粘贴': 'Paste',
    '剪切': 'Cut',
    '撤销': 'Undo',
    '重做': 'Redo',
    '全屏': 'Full Screen',
    '退出全屏': 'Exit Full Screen',
    '刷新': 'Refresh',
    '返回': 'Back',
    '前进': 'Forward',
    '首页': 'Home',
    '我的': 'Mine',
    '设置': 'Setting',
    '关于': 'About',
    '帮助': 'Help',
    '反馈': 'Feedback',
    '退出': 'Logout',
    '登录': 'Login',
    '注册': 'Register',
    '忘记密码': 'Forgot Password',
    '找回密码': 'Retrieve Password',
    '修改密码': 'Change Password',
    '绑定': 'Bind',
    '解绑': 'Unbind',
    '授权': 'Authorize',
    '认证': 'Authenticate',
    '验证': 'Verify',
    '校验': 'Validate',
    '检查': 'Check',
    '测试': 'Test',
    '调试': 'Debug',
    '运行': 'Run',
    '构建': 'Build',
    '部署': 'Deploy',
    '发布': 'Release',
    '上线': 'Online',
    '下线': 'Offline',
    '维护': 'Maintain',
    '升级': 'Upgrade',
    '降级': 'Downgrade',
    '回滚': 'Rollback',
    '备份': 'Backup',
    '恢复': 'Restore',
    '清理': 'Clean',
    '清除': 'Clear',
    '清空': 'Empty',
    '重置': 'Reset',
    '初始化': 'Init',
    '加载': 'Load',
    '渲染': 'Render',
    '挂载': 'Mount',
    '卸载': 'Unmount',
    '更新': 'Update',
    '销毁': 'Destroy',
    '创建': 'Create',
    '插入': 'Insert',
    '追加': 'Append',
    '移除': 'Remove',
    '替换': 'Replace',
    '查找': 'Find',
    '查询': 'Query',
    '获取': 'Get',
    '设置': 'Set',
    '定义': 'Define',
    '声明': 'Declare',
    '引用': 'Reference',
    '调用': 'Call',
    '执行': 'Execute',
    '处理': 'Handle',
    '触发': 'Trigger',
    '监听': 'Listen',
    '观察': 'Observe',
    '订阅': 'Subscribe',
    '发布': 'Publish',
    '分发': 'Dispatch',
    '广播': 'Broadcast',
    '通知': 'Notify',
    '回调': 'Callback',
    '承诺': 'Promise',
    '异步': 'Async',
    '同步': 'Sync',
    '等待': 'Await',
    '延迟': 'Delay',
    '定时器': 'Timer',
    '计数器': 'Counter',
    '循环': 'Loop',
    '遍历': 'Traverse',
    '迭代': 'Iterate',
    '递归': 'Recurse',
    '映射': 'Map',
    '过滤': 'Filter',
    '归约': 'Reduce',
    '拼接': 'Concat',
    '分割': 'Split',
    '截取': 'Slice',
    '连接': 'Join',
    '包含': 'Include',
    '匹配': 'Match',
    '搜索': 'Search',
    '替换': 'Replace',
    '格式化': 'Format',
    '解析': 'Parse',
    '序列化': 'Serialize',
    '反序列化': 'Deserialize',
    '编码': 'Encode',
    '解码': 'Decode',
    '加密': 'Encrypt',
    '解密': 'Decrypt',
    '压缩': 'Compress',
    '解压': 'Decompress',
    '转换': 'Convert',
    '类型': 'Type',
    '值': 'Value',
    '键': 'Key',
    '索引': 'Index',
    '属性': 'Property',
    '方法': 'Method',
    '函数': 'Function',
    '类': 'Class',
    '对象': 'Object',
    '数组': 'Array',
    '字符串': 'String',
    '数字': 'Number',
    '布尔': 'Boolean',
    '空': 'Null',
    '未定义': 'Undefined',
    '符号': 'Symbol',
    '大整数': 'BigInt',
    '日期': 'Date',
    '正则': 'RegExp',
    '错误': 'Error',
    '异常': 'Exception',
    '事件': 'Event',
    'DOM': 'DOM',
    'BOM': 'BOM',
    'Window': 'Window',
    'Document': 'Document',
    'Element': 'Element',
    'Node': 'Node',
    'Attribute': 'Attribute',
    'Style': 'Style',
    'Class': 'Class',
    'ID': 'ID',
    'Tag': 'Tag',
    'Name': 'Name',
    'Value': 'Value',
    'Text': 'Text',
    'HTML': 'HTML',
    'CSS': 'CSS',
    'JS': 'JS',
    'TS': 'TS',
    'Vue': 'Vue',
    'React': 'React',
    'Angular': 'Angular',
    'Node': 'Node',
    'NPM': 'NPM',
    'Yarn': 'Yarn',
    'Webpack': 'Webpack',
    'Vite': 'Vite',
    'Babel': 'Babel',
    'ESLint': 'ESLint',
    'Prettier': 'Prettier',
    'Git': 'Git',
    'GitHub': 'GitHub',
    'GitLab': 'GitLab',
    'CI/CD': 'CI/CD',
    'Docker': 'Docker',
    'K8s': 'K8s',
    'AWS': 'AWS',
    'Azure': 'Azure',
    'GCP': 'GCP',
    'Aliyun': 'Aliyun',
    'Tencent': 'Tencent',
    'Huawei': 'Huawei',
}

def replace_chinese(text):
    # Check for [EN] pattern
    en_match = re.search(r'\[EN\]\s*(.*)', text)
    if en_match:
        return en_match.group(1).strip()

    # Sort keys by length descending
    sorted_keys = sorted(glossary.keys(), key=len, reverse=True)
    
    original_text = text
    for key in sorted_keys:
        if key in text:
            text = text.replace(key, glossary[key])
            
    return text

def process_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        new_lines = []
        modified = False
        
        for line in lines:
            # Check for JS/Vue comments
            # Single line //
            comment_match = re.search(r'(//)\s*(.*)', line)
            if comment_match:
                comment_start = comment_match.start(2)
                comment_content = comment_match.group(2)
                
                if re.search(r'[\u4e00-\u9fff]', comment_content):
                    translated = replace_chinese(comment_content)
                    if translated != comment_content:
                        new_line = line.replace(comment_content, translated)
                        new_lines.append(new_line)
                        modified = True
                        continue
            
            # Block comments /* ... */ (simple single line case)
            block_match = re.search(r'(/\*)\s*(.*?)\s*(\*/)', line)
            if block_match:
                content = block_match.group(2)
                if re.search(r'[\u4e00-\u9fff]', content):
                    translated = replace_chinese(content)
                    if translated != content:
                        new_line = line.replace(content, translated)
                        new_lines.append(new_line)
                        modified = True
                        continue

            new_lines.append(line)
            
        if modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.writelines(new_lines)
            return True
            
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
    return False

def scan_and_fix(root_dirs):
    count = 0
    for root_dir in root_dirs:
        for root, dirs, files in os.walk(root_dir):
            if 'node_modules' in dirs:
                dirs.remove('node_modules')
                
            for file in files:
                if file.endswith(('.js', '.vue', '.ts')):
                    file_path = os.path.join(root, file)
                    if process_file(file_path):
                        print(f"Fixed: {file_path}")
                        count += 1
    return count

print("Starting automated translation of Frontend comments...")
fixed_count = scan_and_fix(['web/src'])
print(f"Finished. Modified {fixed_count} files.")
