import os
import re

# Massive glossary for Go comments
glossary = {
    '参数': 'Parameter',
    '返回': 'Return',
    '成功': 'Success',
    '失败': 'Failed',
    '错误': 'Error',
    '知识库': 'Knowledge Base',
    '文档': 'Document',
    '权限': 'Permission',
    '用户': 'User',
    '组织': 'Organization',
    '模型': 'Model',
    '推理': 'Inference',
    '上下文': 'Context',
    '长度': 'Length',
    '温度': 'Temperature',
    '频率惩罚': 'Frequency Penalty',
    '存在惩罚': 'Presence Penalty',
    '最大标记': 'Max Tokens',
    '视觉支持': 'Vision Support',
    '函数调用': 'Function Calling',
    '索引': 'Index',
    '名称': 'Name',
    '描述': 'Description',
    '类型': 'Type',
    '状态': 'Status',
    '校验': 'Verification',
    '查询': 'Query',
    '获取': 'Get',
    '创建': 'Create',
    '更新': 'Update',
    '删除': 'Delete',
    '日志': 'Log',
    '记录': 'Record',
    '发送': 'Send',
    '请求': 'Request',
    '响应': 'Response',
    '结果': 'Result',
    '输出': 'Output',
    '输入': 'Input',
    '配置': 'Config',
    '初始化': 'Initialize',
    '连接': 'Connect',
    '关闭': 'Close',
    '启动': 'Start',
    '停止': 'Stop',
    '执行': 'Execute',
    '处理': 'Process',
    '解析': 'Parse',
    '转换': 'Convert',
    '生成': 'Generate',
    '上传': 'Upload',
    '下载': 'Download',
    '导入': 'Import',
    '导出': 'Export',
    '批量': 'Batch',
    '列表': 'List',
    '详情': 'Detail',
    '信息': 'Info',
    '数据': 'Data',
    '时间': 'Time',
    '日期': 'Date',
    '密码': 'Password',
    '邮箱': 'Email',
    '手机号': 'Phone',
    '验证码': 'Verification Code',
    '登录': 'Login',
    '注册': 'Register',
    '鉴权': 'Auth',
    '认证': 'Authentication',
    '授权': 'Authorization',
    '角色': 'Role',
    '菜单': 'Menu',
    '按钮': 'Button',
    '接口': 'Interface',
    '服务': 'Service',
    '系统': 'System',
    '环境': 'Environment',
    '开发': 'Dev',
    '测试': 'Test',
    '生产': 'Prod',
    '部署': 'Deploy',
    '运维': 'Ops',
    '监控': 'Monitor',
    '告警': 'Alert',
    '通知': 'Notify',
    '消息': 'Message',
    '队列': 'Queue',
    '缓存': 'Cache',
    '数据库': 'Database',
    '表': 'Table',
    '字段': 'Field',
    '主键': 'Primary Key',
    '外键': 'Foreign Key',
    '事务': 'Transaction',
    '回滚': 'Rollback',
    '提交': 'Commit',
    '锁': 'Lock',
    '并发': 'Concurrency',
    '异步': 'Async',
    '同步': 'Sync',
    '线程': 'Thread',
    '协程': 'Goroutine',
    '进程': 'Process',
    '内存': 'Memory',
    '磁盘': 'Disk',
    '网络': 'Network',
    '协议': 'Protocol',
    '端口': 'Port',
    '地址': 'Address',
    '链接': 'Link',
    '路由': 'Route',
    '中间件': 'Middleware',
    '拦截器': 'Interceptor',
    '过滤器': 'Filter',
    '处理器': 'Handler',
    '控制器': 'Controller',
    '视图': 'View',
    '模板': 'Template',
    '静态资源': 'Static Resource',
    '文件上传': 'File Upload',
    '文件下载': 'File Download',
    '图片': 'Image',
    '视频': 'Video',
    '音频': 'Audio',
    '文本': 'Text',
    '富文本': 'Rich Text',
    '如果没有': 'If not',
    '如果': 'If',
    '否则': 'Otherwise',
    '但是': 'But',
    '或者': 'Or',
    '以及': 'And',
    '因为': 'Because',
    '所以': 'So',
    '为了': 'In order to',
    '注意': 'Note',
    '警告': 'Warning',
    '提示': 'Tip',
    '说明': 'Description',
    '备注': 'Remark',
    'TODO': 'TODO',
    'FIXME': 'FIXME',
    'XXX': 'XXX',
    '暂不支持': 'Not supported yet',
    '不支持': 'Not supported',
    '已废弃': 'Deprecated',
    '使用': 'Use',
    '调用': 'Call',
    '返回': 'Return',
    '需要': 'Need',
    '必须': 'Must',
    '可选': 'Optional',
    '默认': 'Default',
    '最大': 'Max',
    '最小': 'Min',
    '长度': 'Length',
    '范围': 'Range',
    '格式': 'Format',
    '例如': 'Example',
    '比如': 'For example',
    '如': 'Such as',
    '即': 'That is',
    '等': 'Etc',
    '及': 'And',
    '与': 'With',
    '或': 'Or',
    '非': 'Non',
    '是': 'Is',
    '否': 'No',
    '有': 'Has',
    '无': 'No',
    '空': 'Empty',
    '非空': 'Non-empty',
    '真': 'True',
    '假': 'False',
    '高': 'High',
    '低': 'Low',
    '中': 'Medium',
    '大': 'Large',
    '小': 'Small',
    '多': 'Many',
    '少': 'Few',
    '新': 'New',
    '旧': 'Old',
    '前': 'Before',
    '后': 'After',
    '上': 'Up',
    '下': 'Down',
    '左': 'Left',
    '右': 'Right',
    '内': 'Inner',
    '外': 'Outer',
    '主': 'Main',
    '副': 'Sub',
    '父': 'Parent',
    '子': 'Child',
    '根': 'Root',
    '叶': 'Leaf',
    '首': 'First',
    '尾': 'Last',
    '头': 'Head',
    '体': 'Body',
    '脚': 'Foot',
    '开始': 'Start',
    '结束': 'End',
    '暂停': 'Pause',
    '恢复': 'Resume',
    '取消': 'Cancel',
    '确认': 'Confirm',
    '提交': 'Submit',
    '保存': 'Save',
    '加载': 'Load',
    '刷新': 'Refresh',
    '重置': 'Reset',
    '搜索': 'Search',
    '筛选': 'Filter',
    '排序': 'Sort',
    '分页': 'Pagination',
    '跳转': 'Jump',
    '详情': 'Detail',
    '编辑': 'Edit',
    '新增': 'Add',
    '修改': 'Modify',
    '复制': 'Copy',
    '粘贴': 'Paste',
    '剪切': 'Cut',
    '全选': 'Select All',
    '反选': 'Invert Selection',
    '不选': 'Deselect',
    '选中': 'Selected',
    '未选中': 'Unselected',
    '启用': 'Enable',
    '禁用': 'Disable',
    '显示': 'Show',
    '隐藏': 'Hide',
    '展开': 'Expand',
    '收起': 'Collapse',
    '打开': 'Open',
    '关闭': 'Close',
    '锁定': 'Lock',
    '解锁': 'Unlock',
    '授权': 'Authorize',
    '撤销': 'Revoke',
    '审核': 'Audit',
    '通过': 'Pass',
    '拒绝': 'Reject',
    '驳回': 'Reject',
    '发布': 'Publish',
    '下架': 'Unpublish',
    '上线': 'Online',
    '下线': 'Offline',
    '安装': 'Install',
    '卸载': 'Uninstall',
    '升级': 'Upgrade',
    '降级': 'Downgrade',
    '更新': 'Update',
    '修复': 'Fix',
    '优化': 'Optimize',
    '重构': 'Refactor',
    '合并': 'Merge',
    '拆分': 'Split',
    '迁移': 'Migrate',
    '备份': 'Backup',
    '恢复': 'Restore',
    '清理': 'Clean',
    '清除': 'Clear',
    '清空': 'Empty',
    '删除': 'Delete',
    '移除': 'Remove',
    '销毁': 'Destroy',
    '回收': 'Recycle',
    '垃圾回收': 'GC',
    '资源': 'Resource',
    '资产': 'Asset',
    '资金': 'Fund',
    '账户': 'Account',
    '余额': 'Balance',
    '积分': 'Points',
    '等级': 'Level',
    '经验': 'Exp',
    '排名': 'Rank',
    '榜单': 'Leaderboard',
    '成就': 'Achievement',
    '任务': 'Task',
    '活动': 'Activity',
    '奖励': 'Reward',
    '礼包': 'Gift',
    '优惠': 'Discount',
    '折扣': 'Discount',
    '价格': 'Price',
    '金额': 'Amount',
    '数量': 'Quantity',
    '总计': 'Total',
    '合计': 'Sum',
    '平均': 'Average',
    '最大值': 'Max',
    '最小值': 'Min',
    '中位数': 'Median',
    '众数': 'Mode',
    '方差': 'Variance',
    '标准差': 'Std Dev',
    '比例': 'Ratio',
    '百分比': 'Percentage',
    '增长率': 'Growth Rate',
    '转化率': 'Conversion Rate',
    '留存率': 'Retention Rate',
    '流失率': 'Churn Rate',
    '活跃度': 'Activity',
    '满意度': 'Satisfaction',
    '评分': 'Rating',
    '评论': 'Comment',
    '点赞': 'Like',
    '收藏': 'Favorite',
    '分享': 'Share',
    '关注': 'Follow',
    '粉丝': 'Fan',
    '好友': 'Friend',
    '群组': 'Group',
    '社区': 'Community',
    '论坛': 'Forum',
    '帖子': 'Post',
    '文章': 'Article',
    '博客': 'Blog',
    '新闻': 'News',
    '公告': 'Notice',
    '通知': 'Notification',
    '私信': 'DM',
    '聊天': 'Chat',
    '会话': 'Session',
    '房间': 'Room',
    '频道': 'Channel',
    '直播': 'Live',
    '视频': 'Video',
    '音频': 'Audio',
    '图片': 'Image',
    '文件': 'File',
    '目录': 'Directory',
    '路径': 'Path',
    '链接': 'Link',
    'URL': 'URL',
    'URI': 'URI',
    'IP': 'IP',
    '域名': 'Domain',
    '主机': 'Host',
    '服务器': 'Server',
    '客户端': 'Client',
    '浏览器': 'Browser',
    '设备': 'Device',
    '系统': 'System',
    '平台': 'Platform',
    '版本': 'Version',
    '构建': 'Build',
    '编译': 'Compile',
    '打包': 'Package',
    '发布': 'Release',
    '部署': 'Deploy',
    '运行': 'Run',
    '调试': 'Debug',
    '测试': 'Test',
    '验证': 'Verify',
    '演示': 'Demo',
    '示例': 'Example',
    '文档': 'Doc',
    '手册': 'Manual',
    '指南': 'Guide',
    '教程': 'Tutorial',
    'FAQ': 'FAQ',
    '帮助': 'Help',
    '支持': 'Support',
    '反馈': 'Feedback',
    '建议': 'Suggestion',
    '投诉': 'Complaint',
    '举报': 'Report',
    '联系': 'Contact',
    '关于': 'About',
    '隐私': 'Privacy',
    '条款': 'Terms',
    '协议': 'Agreement',
    '版权': 'Copyright',
    '授权': 'License',
    '商标': 'Trademark',
    '专利': 'Patent',
    '法律': 'Legal',
    '合规': 'Compliance',
    '安全': 'Safety',
    '风险': 'Risk',
    '漏洞': 'Vulnerability',
    '攻击': 'Attack',
    '防御': 'Defense',
    '加密': 'Encrypt',
    '解密': 'Decrypt',
    '签名': 'Sign',
    '验签': 'Verify Sign',
    '哈希': 'Hash',
    '摘要': 'Digest',
    '随机': 'Random',
    '唯一': 'Unique',
    'ID': 'ID',
    'UUID': 'UUID',
    'GUID': 'GUID',
    'Token': 'Token',
    'Session': 'Session',
    'Cookie': 'Cookie',
    'Header': 'Header',
    'Body': 'Body',
    'Query': 'Query',
    'Param': 'Param',
    'Form': 'Form',
    'JSON': 'JSON',
    'XML': 'XML',
    'Protobuf': 'Protobuf',
    'Thrift': 'Thrift',
    'Avro': 'Avro',
    'Parquet': 'Parquet',
    'ORC': 'ORC',
    'CSV': 'CSV',
    'TSV': 'TSV',
    'Excel': 'Excel',
    'Word': 'Word',
    'PPT': 'PPT',
    'PDF': 'PDF',
    'TXT': 'TXT',
    'Log': 'Log',
    'Config': 'Config',
    'Data': 'Data',
    'Code': 'Code',
    'Text': 'Text',
    'Bin': 'Bin',
    'Image': 'Image',
    'Audio': 'Audio',
    'Video': 'Video',
    'Stream': 'Stream',
    'Buffer': 'Buffer',
    'Cache': 'Cache',
    'Queue': 'Queue',
    'Stack': 'Stack',
    'List': 'List',
    'Map': 'Map',
    'Set': 'Set',
    'Tree': 'Tree',
    'Graph': 'Graph',
    'Vector': 'Vector',
    'Matrix': 'Matrix',
    'Tensor': 'Tensor',
    'Scalar': 'Scalar',
    'Number': 'Number',
    'String': 'String',
    'Bool': 'Bool',
    'Object': 'Object',
    'Array': 'Array',
    'Function': 'Function',
    'Class': 'Class',
    'Interface': 'Interface',
    'Struct': 'Struct',
    'Enum': 'Enum',
    'Const': 'Const',
    'Var': 'Var',
    'Let': 'Let',
    'Type': 'Type',
    'Value': 'Value',
    'Key': 'Key',
    'Index': 'Index',
    'Pointer': 'Pointer',
    'Reference': 'Reference',
    'Value': 'Value',
    'Null': 'Null',
    'Nil': 'Nil',
    'None': 'None',
    'True': 'True',
    'False': 'False',
    'Error': 'Error',
    'Exception': 'Exception',
    'Panic': 'Panic',
    'Fatal': 'Fatal',
    'Warning': 'Warning',
    'Info': 'Info',
    'Debug': 'Debug',
    'Trace': 'Trace',
    'All': 'All',
    'Off': 'Off',
    'On': 'On',
    'Enable': 'Enable',
    'Disable': 'Disable',
    'Start': 'Start',
    'Stop': 'Stop',
    'Restart': 'Restart',
    'Reload': 'Reload',
    'Status': 'Status',
    'Health': 'Health',
    'Metrics': 'Metrics',
    'Trace': 'Trace',
    'Profile': 'Profile',
    'Dump': 'Dump',
    'Log': 'Log',
    'Console': 'Console',
    'Terminal': 'Terminal',
    'Shell': 'Shell',
    'Bash': 'Bash',
    'Zsh': 'Zsh',
    'Fish': 'Fish',
    'PowerShell': 'PowerShell',
    'CMD': 'CMD',
    'CLI': 'CLI',
    'GUI': 'GUI',
    'UI': 'UI',
    'UX': 'UX',
    'API': 'API',
    'SDK': 'SDK',
    'Lib': 'Lib',
    'Framework': 'Framework',
    'Platform': 'Platform',
    'OS': 'OS',
    'Kernel': 'Kernel',
    'Driver': 'Driver',
    'Firmware': 'Firmware',
    'Hardware': 'Hardware',
    'Software': 'Software',
    'App': 'App',
    'Service': 'Service',
    'Daemon': 'Daemon',
    'Job': 'Job',
    'Task': 'Task',
    'Process': 'Process',
    'Thread': 'Thread',
    'Goroutine': 'Goroutine',
    'Actor': 'Actor',
    'Worker': 'Worker',
    'Master': 'Master',
    'Slave': 'Slave',
    'Leader': 'Leader',
    'Follower': 'Follower',
    'Primary': 'Primary',
    'Secondary': 'Secondary',
    'Replica': 'Replica',
    'Shard': 'Shard',
    'Partition': 'Partition',
    'Cluster': 'Cluster',
    'Node': 'Node',
    'Pod': 'Pod',
    'Container': 'Container',
    'Image': 'Image',
    'Volume': 'Volume',
    'Network': 'Network',
    'Service': 'Service',
    'Ingress': 'Ingress',
    'ConfigMap': 'ConfigMap',
    'Secret': 'Secret',
    'Deployment': 'Deployment',
    'StatefulSet': 'StatefulSet',
    'DaemonSet': 'DaemonSet',
    'Job': 'Job',
    'CronJob': 'CronJob',
    'Namespace': 'Namespace',
    'Context': 'Context',
    'User': 'User',
    'Role': 'Role',
    'Binding': 'Binding',
    'Policy': 'Policy',
    'Rule': 'Rule',
    'Subject': 'Subject',
    'Object': 'Object',
    'Action': 'Action',
    'Effect': 'Effect',
    'Condition': 'Condition',
    'Resource': 'Resource',
    'Scope': 'Scope',
    'Level': 'Level',
    'Priority': 'Priority',
    'Weight': 'Weight',
    'Score': 'Score',
    'Rank': 'Rank',
    'Order': 'Order',
    'Sort': 'Sort',
    'Filter': 'Filter',
    'Limit': 'Limit',
    'Offset': 'Offset',
    'Page': 'Page',
    'Size': 'Size',
    'Total': 'Total',
    'Count': 'Count',
    'Sum': 'Sum',
    'Avg': 'Avg',
    'Min': 'Min',
    'Max': 'Max',
    'Group': 'Group',
    'Join': 'Join',
    'Union': 'Union',
    'Select': 'Select',
    'Insert': 'Insert',
    'Update': 'Update',
    'Delete': 'Delete',
    'Create': 'Create',
    'Drop': 'Drop',
    'Alter': 'Alter',
    'Truncate': 'Truncate',
    'Grant': 'Grant',
    'Revoke': 'Revoke',
    'Commit': 'Commit',
    'Rollback': 'Rollback',
    'Begin': 'Begin',
    'End': 'End',
    'Transaction': 'Transaction',
    'Lock': 'Lock',
    'Unlock': 'Unlock',
    'Wait': 'Wait',
    'Notify': 'Notify',
    'Signal': 'Signal',
    'Broadcast': 'Broadcast',
    'Sleep': 'Sleep',
    'Wakeup': 'Wakeup',
    'Yield': 'Yield',
    'Return': 'Return',
    'Break': 'Break',
    'Continue': 'Continue',
    'Goto': 'Goto',
    'Throw': 'Throw',
    'Catch': 'Catch',
    'Finally': 'Finally',
    'Try': 'Try',
    'Except': 'Except',
    'Raise': 'Raise',
    'Import': 'Import',
    'Export': 'Export',
    'Package': 'Package',
    'Module': 'Module',
    'Class': 'Class',
    'Interface': 'Interface',
    'Trait': 'Trait',
    'Mixin': 'Mixin',
    'Extends': 'Extends',
    'Implements': 'Implements',
    'Public': 'Public',
    'Private': 'Private',
    'Protected': 'Protected',
    'Internal': 'Internal',
    'Static': 'Static',
    'Final': 'Final',
    'Abstract': 'Abstract',
    'Virtual': 'Virtual',
    'Override': 'Override',
    'New': 'New',
    'Delete': 'Delete',
    'This': 'This',
    'Super': 'Super',
    'Self': 'Self',
    'Parent': 'Parent',
    'Child': 'Child',
    'Root': 'Root',
    'Leaf': 'Leaf',
    'Node': 'Node',
    'Edge': 'Edge',
    'Vertex': 'Vertex',
    'Graph': 'Graph',
    'Tree': 'Tree',
    'List': 'List',
    'Map': 'Map',
    'Set': 'Set',
    'Queue': 'Queue',
    'Stack': 'Stack',
    'Heap': 'Heap',
    'Hash': 'Hash',
    'Array': 'Array',
    'String': 'String',
    'Int': 'Int',
    'Float': 'Float',
    'Bool': 'Bool',
    'Byte': 'Byte',
    'Char': 'Char',
    'Rune': 'Rune',
    'Void': 'Void',
    'Null': 'Null',
    'Nil': 'Nil',
    'None': 'None',
    'Undefined': 'Undefined',
    'NaN': 'NaN',
    'Infinity': 'Infinity',
    'True': 'True',
    'False': 'False',
}

def replace_chinese(text):
    # Check for [EN] pattern
    en_match = re.search(r'\[EN\]\s*(.*)', text)
    if en_match:
        return en_match.group(1).strip()

    # Sort keys by length descending
    sorted_keys = sorted(glossary.keys(), key=len, reverse=True)
    
    original_text = text
    for key in sorted_keys:
        if key in text:
            text = text.replace(key, glossary[key])
            
    # If we replaced something, return the new text
    # If not, return original (maybe it's complex Chinese we can't translate yet)
    return text

def process_file(file_path):
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()
        
        new_lines = []
        modified = False
        
        for line in lines:
            # Check for Go comments
            comment_match = re.search(r'(//|/\*)\s*(.*)', line)
            if comment_match:
                comment_start = comment_match.start(2)
                comment_content = comment_match.group(2)
                
                # Only translate if it has Chinese
                if re.search(r'[\u4e00-\u9fff]', comment_content):
                    translated = replace_chinese(comment_content)
                    if translated != comment_content:
                        # Reconstruct line
                        # Be careful with */ at the end
                        suffix = ''
                        if line.strip().endswith('*/'):
                            if translated.endswith('*/'):
                                pass # already has it
                            else:
                                # It's tricky to reconstruct exactly if we just replaced content
                                # Let's just replace the content part we found
                                pass
                        
                        # Simple replacement in the line
                        # This is safer than reconstructing
                        new_line = line.replace(comment_content, translated)
                        new_lines.append(new_line)
                        modified = True
                        continue
            
            new_lines.append(line)
            
        if modified:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.writelines(new_lines)
            return True
            
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
    return False

def scan_and_fix(root_dirs):
    count = 0
    for root_dir in root_dirs:
        for root, dirs, files in os.walk(root_dir):
            for file in files:
                if file.endswith('.go'):
                    file_path = os.path.join(root, file)
                    if process_file(file_path):
                        print(f"Fixed: {file_path}")
                        count += 1
    return count

print("Starting automated translation of Go comments...")
fixed_count = scan_and_fix(['internal', 'pkg'])
print(f"Finished. Modified {fixed_count} files.")
