syntax = "proto3";

package operate_service;

import "google/protobuf/empty.proto";
import "proto/common/common.proto";

option go_package = "github.com/UnicomAI/wanwu/api/proto/operate-service";

service OperateService {
    rpc CreateSystemCustomTab(CreateSystemCustomTabReq) returns (google.protobuf.Empty) {}
    rpc CreateSystemCustomLogin(CreateSystemCustomLoginReq) returns (google.protobuf.Empty) {}
    rpc CreateSystemCustomHome(CreateSystemCustomHomeReq) returns (google.protobuf.Empty) {}
    rpc GetSystemCustom(GetSystemCustomReq) returns (SystemCustom) {}

    rpc AddClientRecord(AddClientRecordReq) returns (google.protobuf.Empty) {}
    rpc GetClientStatistic(GetClientStatisticReq) returns (ClientStatistic) {}
}

message CreateSystemCustomTabReq {
    string orgId = 1; // 租户ID [EN] Tenant ID
    string userId = 2; // 用户ID [EN] User ID
    string mode = 3; // 模式 [EN] model
    Tab tab = 4; // 标签页信息 [EN] Tab information
}

message CreateSystemCustomLoginReq {
    string orgId = 1; // 租户ID [EN] Tenant ID
    string userId = 2; // 用户ID [EN] User ID
    string mode = 3;
    Login login = 4; // 登录页 [EN] Login page
}

message CreateSystemCustomHomeReq {
    string orgId = 1; // 租户ID [EN] Tenant ID
    string userId = 2; // 用户ID [EN] User ID
    string mode = 3;
    Home home = 4; // 标题 [EN] title
}

message GetSystemCustomReq {
    string mode = 1; // 模式 [EN] model
}

message SystemCustom {
    Login login = 1; // 登录页 [EN] Login page
    Tab tab = 2; // logo
    Home home = 3; // 标题 [EN] title
}

message Tab {
    string tabLogoPath = 1; // 标签页logo路径 [EN] Tab logo path
    string tabTitle = 2; // 标签页标题 [EN] Tab title
}

message Login {
    string loginBgPath = 1; // 登录页背景图 [EN] Login page background image
    string loginLogo = 2; // 登录页logo路径 [EN] Login page logo path
    string loginWelcomeText = 3; // 登录页欢迎词 [EN] Login page welcome message
    string loginButtonColor = 4; // 登录按钮颜色 [EN] Login button color
}

message Home {
    string homeLogoPath = 1; // 平台logo路径 [EN] Platform logo path
    string homeName = 2; // 平台名称 [EN] Platform name
    string homeBgColor = 3; // 平台背景颜色 [EN] Platform background color
}

message AddClientRecordReq {
    string clientId =1 ;
}

message GetClientStatisticReq{
    string startDate = 1;
    string endDate = 2;
}

message ClientStatistic{
    ClientOverViewInfo overview = 1;
    ClientTrendInfo trend = 2;
}

message ClientOverViewInfo{
    ClientOverviewItem cumulative = 1; // 累计 [EN] Grand total
    ClientOverviewItem new = 2; // 新增 [EN] New
    ClientOverviewItem active = 3; // 日活 [EN] Daily activity
}

message ClientOverviewItem {
    float value = 1;
    float periodOverperiod = 2;
}

message ClientTrendInfo{
    common.StatisticChart client = 1;
}

